### ISSUE TITLE
Use 1px marquee border when zooming

### ISSUE THREAD

**Issue by sos4nt** [aseprite/aseprite#3283] opened 2022-05-11 16:37 UTC
I've noticed that the marquee selection border is being zoomed along with the canvas. This makes it much harder to make a selection because many pixels are being obstructed by the selection.

It would be cleaner to have a 1px selection border, i.e. the same thickness that's being used for the marching ants border after releasing the mouse button:

<img width="750" alt="1px-marquee" src="https://user-images.githubusercontent.com/28232/167905991-64ae7f5b-3998-4670-a95d-bbcfddd12486.png">

**Comment by dacap** [comment] 2022-05-12 15:17
Hi @sos4nt, actually this is a duplicate of #2852, anyway it's nice to have a screenshot about the general idea.

We have to refactor/change the internal handling of selection-like tools to improve the general feedback and make the border as small as possible.

**Closed by dacap** 2022-05-12 15:17 UTC
Labels: duplicate, feature, ui
