### ISSUE TITLE
Index mode spray does not handle masked color as expected

### ISSUE THREAD

**Issue by hapiel** [aseprite/aseprite#3063] opened 2021-11-21 15:51 UTC
In indexed mode, when drawing with the masked color with the spray tool, on a non background layer, in "simple ink" mode, if the masked color does not have alpha 0, it either does not work or it attempts to draw another color.
See demonstration:

![aseprite](https://user-images.githubusercontent.com/4511993/142769043-a8841d44-14a1-448e-b008-292a69a69266.gif)

Spray does draw a color (the one closest to the masked color) with right click if you have mask on right and random color on left, but not if you do that the other way around.

This behaviour is different from the pencil tool, the pencil tool behaves as I expect. Therefor the spray tool behaviour is unexpected.

### Aseprite and System version

* Aseprite version: v1.3-beta6-x64
* System: Windows 10

**Comment by hapiel** [comment] 2021-11-21 15:51
See also the relevant Discord discussion:

https://discord.com/channels/324979738533822464/348146938530496513/911989782501003315

**Comment by Gasparoken** [comment] 2021-11-21 18:29
Thanks for this report @hapiel! We'll fix it.

**Comment by iamOgunyinka** [comment] 2021-12-10 12:14
@Gasparoken can you assign this to me? I can look into it.

**Comment by iamOgunyinka** [comment] 2021-12-13 09:04
@Gasparoken I can't reproduce this.

**Comment by Gasparoken** [comment] 2021-12-13 10:32
It can be reproduced by doing this:
- New sprite - Indexed mode - transparent background
- Use the PaintBucket tool to paint the entire sprite green (for example)
- Select index 0 as the foreground color (it is the transparent color of this sprite)
- Select the Pencil tool and draw on the canvas: you'll see that a stroke is being drawn
- Select the Spray tool and draw on the canvas: you'll see nothing is drawn (the expected behavior is like the Pencil tool)

**Closed** 2022-09-20 17:38 UTC
Labels: bug, high priority, time-3
