### ISSUE TITLE
[Beta] Paint Bucket ignores Right-click preference

### ISSUE THREAD

**Issue by not-surt** [aseprite/aseprite#3550] opened 2022-10-07 20:12 UTC
In v1.3-beta21 when the _Editor_ _Right-click_ preference is set to _Pick foreground color_ right-clicking with the _Paint Bucket_ tool still behaves as though the _Right-click_ preference is set to _Paint with background color_.

EDIT:
That's how it functions in Indexed mode.
In RGB mode it seems to do nothing, neither picking a colour nor painting a colour.

### Aseprite and System version

* Aseprite version: v1.3-beta21-x64, installer
* System: Windows 10

**Comment by martincapello** [comment] 2022-10-12 17:27
Hey there, I have been trying to reproduce this without success 😞 
I tested this in the same version you specified. Is there a chance that maybe I need to set or do anything else? Could you record a video showing the issue? This could be helpful

**Comment by not-surt** [comment] 2022-10-12 20:12
It would consistently work incorrectly.

I tried renaming the config directory and it is now working as expected from the otherwise default config.

So I guess it's conflicting with some other setting I was using. No idea what it might be.

I've still got the original config files that caused the issue if you're interested.

**Comment by martincapello** [comment] 2022-10-12 20:18
Oh I see.

> I've still got the original config files that caused the issue if you're interested.

Sure! You can attach them in a new comment on this issue

**Comment by not-surt** [comment] 2022-10-12 20:29
Problematic config attached.
[Aseprite.zip](https://github.com/aseprite/aseprite/files/9768469/Aseprite.zip)

**Comment by martincapello** [comment] 2022-10-27 11:52
I've been looking at the source code and this is happening because the paint bucket is used in combination with the shading ink:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/5520828/198275433-d5d2d707-9076-43a4-92f5-da3260c0d511.png">

This is the piece of code that does it:
https://github.com/aseprite/aseprite/blob/7309c61c867f16bcb526c16a85c6efec7e55a511/src/app/tools/active_tool.cpp#L231-L239

More specifically:
```c++
(tool->getInk(0)->isPaint() && !shadingMode)
```

This is because the shading ink uses the right-click to "move" to the right through the shading colors. But when you don't have shading colors selected, it behaves like the regular paint bucket.

So, I will close this and remove the "bug" label. If anybody thinks this needs some change, we can reopen it later.

**Closed by martincapello** 2022-10-27 11:52 UTC
Labels: bug, high priority, time-5, wip

**Comment by KasumiArai** [comment] 2022-10-28 05:05
I think I remember the issue you refer to. It is here: https://github.com/aseprite/aseprite/issues/236

**Comment by dacap** [comment] 2022-10-28 12:24
Thanks @KasumiArai :heart: I remembered that I thought about this in the past :relaxed:
