### ISSUE TITLE
Multiple definition errors while linking Aseprite

### ISSUE THREAD

**Issue by thechubbypanda** [aseprite/aseprite#2387] opened 2020-05-17 20:52 UTC
### Aseprite and System version

* Aseprite version: Release v1.2.18
* System: Linux, Latest, Arch

```
[1/1] Linking CXX executable bin/aseprite
FAILED: bin/aseprite 
: && /usr/bin/c++  -Wall -Wno-switch -O2 -g -DNDEBUG   src/CMakeFiles/aseprite.dir/main/main.cpp.o  -o bin/aseprite  lib/libapp-lib.a  lib/libclip.a  -lxcb  -lpthread  lib/libdio-lib.a  lib/libfilters-lib.a  lib/libflic-lib.a  lib/libtga-lib.a  lib/librender-lib.a  lib/libdoc-lib.a  lib/libfixmath-lib.a  lib/libui-lib.a  lib/liblaf-os.a  lib/liblaf-gfx.a  lib/liblaf-ft.a  /home/keval/Downloads/Skia-Linux-Release-x64/out/Release-x64/libskia.a  /usr/lib/libGL.so  /usr/lib/libfontconfig.so  /usr/lib/libSM.so  /usr/lib/libICE.so  /usr/lib/libX11.so  /usr/lib/libXext.so  /usr/lib/libXcursor.so  /home/keval/Downloads/Skia-Linux-Release-x64/out/Release-x64/libskshaper.a  lib/libobs.a  lib/libundo.a  lib/libcmark.a  lib/libjpeg.a  lib/libgiflib.a  lib/libwebpdemux.a  lib/libwebpmux.a  lib/libwebp.a  -lpthread  lib/libfreetype.a  lib/libharfbuzz.a  lib/libfreetype.a  lib/libharfbuzz.a  lib/libpng16.a  -lm  /usr/lib/libbz2.so  lib/libjson11.a  lib/libarchive.a  /usr/lib/liblz4.so  /usr/lib/libzstd.so  /usr/lib/libcrypto.so  /usr/lib/libexpat.so  /usr/lib/libacl.so  /usr/lib/libssl.so  lib/libfmt.a  lib/libtinyexpr.a  lib/liblauxlib.a  lib/liblua.a  lib/liblualib.a  lib/libupdater-lib.a  lib/libcfg-lib.a  lib/libver-lib.a  lib/libtinyxml.a  lib/libnet-lib.a  lib/liblaf-base.a  lib/libmodpbase64.a  /usr/lib/libdl.so  lib/libcurl.a  lib/libz.a  -ldl  -lidn  -lldap && :
/usr/bin/ld: lib/libwebp.a(alpha_processing.c.o): in function `WebPMultARGBRow_C':
/home/keval/Downloads/Aseprite-v1.2.18-Source/build/../third_party/libwebp/src/dsp/alpha_processing.c:140: multiple definition of `WebPMultARGBRow_C'; /home/keval/Downloads/Skia-Linux-Release-x64/out/Release-x64/libskia.a(libwebp.alpha_processing.o):alpha_processing.c:(.text.WebPMultARGBRow_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(alpha_processing.c.o): in function `WebPMultRow_C':
/home/keval/Downloads/Aseprite-v1.2.18-Source/build/../third_party/libwebp/src/dsp/alpha_processing.c:161: multiple definition of `WebPMultRow_C'; /home/keval/Downloads/Skia-Linux-Release-x64/out/Release-x64/libskia.a(libwebp.alpha_processing.o):alpha_processing.c:(.text.WebPMultRow_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(alpha_processing.c.o): in function `WebPMultARGBRows':
/home/keval/Downloads/Aseprite-v1.2.18-Source/build/../third_party/libwebp/src/dsp/alpha_processing.c:190: multiple definition of `WebPMultARGBRows'; /home/keval/Downloads/Skia-Linux-Release-x64/out/Release-x64/libskia.a(libwebp.alpha_processing.o):alpha_processing.c:(.text.WebPMultARGBRows+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(alpha_processing.c.o): in function `WebPMultRows':
/home/keval/Downloads/Aseprite-v1.2.18-Source/build/../third_party/libwebp/src/dsp/alpha_processing.c:198: multiple definition of `WebPMultRows'; /home/keval/Downloads/Skia-Linux-Release-x64/out/Release-x64/libskia.a(libwebp.alpha_processing.o):alpha_processing.c:(.text.WebPMultRows+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(alpha_processing.c.o): in function `WebPInitAlphaProcessing':
/home/keval/Downloads/Aseprite-v1.2.18-Source/build/../third_party/libwebp/src/dsp/alpha_processing.c:412: multiple definition of `WebPInitAlphaProcessing'; /home/keval/Downloads/Skia-Linux-Release-x64/out/Release-x64/libskia.a(libwebp.alpha_processing.o):alpha_processing.c:(.text.WebPInitAlphaProcessing+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(dec.c.o): in function `VP8DspInit':
/home/keval/Downloads/Aseprite-v1.2.18-Source/build/../third_party/libwebp/src/dsp/dec.c:744: multiple definition of `VP8DspInit'; /home/keval/Downloads/Skia-Linux-Release-x64/out/Release-x64/libskia.a(libwebp.dec.o):dec.c:(.text.VP8DspInit+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(filters.c.o): in function `VP8FiltersInit':
/home/keval/Downloads/Aseprite-v1.2.18-Source/build/../third_party/libwebp/src/dsp/filters.c:241: multiple definition of `VP8FiltersInit'; /home/keval/Downloads/Skia-Linux-Release-x64/out/Release-x64/libskia.a(libwebp.filters.o):filters.c:(.text.VP8FiltersInit+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(lossless.c.o): in function `VP8LAddGreenToBlueAndRed_C':
/home/keval/Downloads/Aseprite-v1.2.18-Source/build/../third_party/libwebp/src/dsp/lossless.c:245: multiple definition of `VP8LAddGreenToBlueAndRed_C'; /home/keval/Downloads/Skia-Linux-Release-x64/out/Release-x64/libskia.a(libwebp.lossless.o):lossless.c:(.text.VP8LAddGreenToBlueAndRed_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(lossless.c.o): in function `VP8LTransformColorInverse_C':
/home/keval/Downloads/Aseprite-v1.2.18-Source/build/../third_party/libwebp/src/dsp/lossless.c:273: 

...

collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

Used latest prebuilt skia

**Comment by dacap** [comment] 2020-05-18 21:13
Hi @thechubbypanda, could you please check the `master` version? (update submodules) this might be fixed.

**Comment by thechubbypanda** [comment] 2020-05-19 10:49
I'm afraid the changes have fixed the situation, I still receive similar if not the same errors. 

I used the same prebuilt skia, perhaps I should build that from source as well?

Just for clarification, I deleted the aseprite repository entirely and recloned it along with the submodules.

**Comment by thechubbypanda** [comment] 2020-05-19 10:58
`$ ninja aseprite | grep -v "webp"`
```
[1/1] Linking CXX executable bin/aseprite
FAILED: bin/aseprite 
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

Shows all the problems are indeed with webp

**Comment by Psycho7777** [comment] 2020-05-19 19:09
@thechubbypanda did you manage to fix the error?

**Comment by thechubbypanda** [comment] 2020-05-19 19:19
I'm afraid not, I realised the AUR package works so I have a working version, still trying to figure out what's happening differently when I build it myself

**Comment by rouhannb** [comment] 2020-05-30 16:24
I’m getting those same errors when compiling with the prebuilt skia library on both 1.2.18 and 1.2.19, though I have been able to compile 1.2.18, at least as far back as April 24. Maybe a library update broke something?

**Comment by enderger** [comment] 2020-06-13 20:53
I am having the same problem using aseprite under OpenSUSE Tumbleweed. Same error, master branch.

**Comment by enderger** [comment] 2020-06-13 21:07
Since I hopped after the change, I can confirm that it is a version issue: from the version shipped with Ubuntu's apt repo and the one in OpenSUSE Tumbleweed's RPM repos.

**Comment by enderger** [comment] 2020-06-13 21:32
-------------------------------------------------------------------
Wed Apr  1 07:25:56 UTC 2020 - Martin Pluskal <mpluskal@suse.com>

- Update to version 1.1.0:
  * API changes:
    - libwebp:
      WebPMalloc
    - extras:
      WebPUnmultiplyARGB
  * alpha decode fix
  * toolchain updates and bug fixes

From the libwebp OBS Changelog, they changed the API

**Comment by enderger** [comment] 2020-06-14 01:11
Hey, I've found a workaround and will be pushing a small fix to the INSTALL.md file:

1. Follow the compile instructions for the latest Asprite Skia commit.
2. Compile aseprite USING THE `aseprite` task: the install task does not like self-compiled Skias
3. Copy the aseprite binary to somewhere on the path.

And it should compile.

**Comment by CaptainKraft** [comment] 2020-06-20 22:59
Took me a while to figure it out, but I'm having this exact issue. Just thought I'd bump this issue.

**Comment by saranvdev** [comment] 2020-07-31 17:42
bump

**Comment by tlesne** [comment] 2020-08-17 09:42
I have the same issue on Fedora using latest master (f3e9978bb002673c2fa75c6ec7c70e270a4d969f) with prebuilt skia library (https://github.com/aseprite/skia/releases/tag/m81-b607b32047).

Ninja is maybe trying to link against my installed libwebp version (1.1.0)?

**Comment by Aoczs** [comment] 2020-09-22 13:38
I have the same issue when I compile aseprite on ArchLinux.
But when I execute the same operations with same git repositories('Aseprite lastest release' and 'prebuild skia library lastest release') on Ubuntu20.04, the compilation is successful...
Maybe the ArchLinux's libraries are different(at leaset not divide to 'libXX' and 'libXX-dev')?

**Comment by Aoczs** [comment] 2020-09-23 10:34
> I have the same issue when I compile aseprite on ArchLinux.
> But when I execute the same operations with same git repositories('Aseprite lastest release' and 'prebuild skia library lastest release') on Ubuntu20.04, the compilation is successful...
> Maybe the ArchLinux's libraries are different(at leaset not divide to 'libXX' and 'libXX-dev')?

After the failure of self-compilation, I tried to use [the AUR‘s packaged Aseprite](https://aur.archlinux.org/packages/aseprite).
Because of the network problem, I tried to modify the PKGBUILD file myself.
Then I got the same error. But I found a argument of CMake in this PKGBUILD file:
```
cmake \
    -DWITH_WEBP_SUPPROT=ON
```
I turn off this option and execute rest same operations:
```
cmake \
    -DWITH_WEBP_SUPPORT=OFF
```
Finally the compilation is successful. I get a usable Aseprite.
But this kind of Aseprite exactly can not support the .WebP format pictures. There are no webp options in open file or export file.

**Comment by Aoczs** [comment] 2020-09-23 12:34
I find an another usable solution.

the build will stop at the last subcommand. This command links all libraries to a binary executable file "aseprite".
```
[1/1] Linking CXX executable bin/aseprite
FAILED: bin/aseprite 
: && /usr/bin/c++  -Wall -Wno-switch -O2 -g -DNDEBUG   src/CMakeFiles/aseprite.dir/main/main.cpp.o  -o bin/aseprite  lib/libapp-lib.a  lib/libclip.a  -lxcb  -lpthread  lib/libdio-lib.a  lib/libfilters-lib.a  lib/libflic-lib.a  lib/libtga-lib.a  lib/librender-lib.a  lib/libdoc-lib.a  lib/libfixmath-lib.a  lib/libui-lib.a  lib/liblaf-os.a  lib/liblaf-gfx.a  lib/liblaf-ft.a  /home/keval/Downloads/Skia-Linux-Release-x64/out/Release-x64/libskia.a  /usr/lib/libGL.so  /usr/lib/libfontconfig.so  /usr/lib/libSM.so  /usr/lib/libICE.so  /usr/lib/libX11.so  /usr/lib/libXext.so  /usr/lib/libXcursor.so  /home/keval/Downloads/Skia-Linux-Release-x64/out/Release-x64/libskshaper.a  lib/libobs.a  lib/libundo.a  lib/libcmark.a  lib/libjpeg.a  lib/libgiflib.a  lib/libwebpdemux.a  lib/libwebpmux.a  lib/libwebp.a  -lpthread  lib/libfreetype.a  lib/libharfbuzz.a  lib/libfreetype.a  lib/libharfbuzz.a  lib/libpng16.a  -lm  /usr/lib/libbz2.so  lib/libjson11.a  lib/libarchive.a  /usr/lib/liblz4.so  /usr/lib/libzstd.so  /usr/lib/libcrypto.so  /usr/lib/libexpat.so  /usr/lib/libacl.so  /usr/lib/libssl.so  lib/libfmt.a  lib/libtinyexpr.a  lib/liblauxlib.a  lib/liblua.a  lib/liblualib.a  lib/libupdater-lib.a  lib/libcfg-lib.a  lib/libver-lib.a  lib/libtinyxml.a  lib/libnet-lib.a  lib/liblaf-base.a  lib/libmodpbase64.a  /usr/lib/libdl.so  lib/libcurl.a  lib/libz.a  -ldl  -lidn  -lldap && :
```

Now refer to my first reply: I think it's the **conflict** between ".../Skia-Linux-Release-x64/out/Release-x64/libskia.a" and "lib/libwebp.a"
> This looks like the prebuild skia static library ".../Skia-Linux-Release-x64/out/Release-x64/libskia.a" conflicts with the ninja-created libwebp static library "lib/libwebp.a".
> ```
> /usr/bin/ld: lib/libwebp.a(alpha_processing.c.o): in function `WebPMultARGBRow_C':
> /home/keval/Downloads/Aseprite-v1.2.18-Source/build/../third_party/libwebp/src/dsp/alpha_processing.c:140: multiple definition of `WebPMultARGBRow_C'; /home/keval/Downloads/Skia-Linux-Release-x64/out/Release-x64/libskia.a(libwebp.alpha_processing.o):alpha_processing.c:(.text.WebPMultARGBRow_C+0x0): first defined here
> ```
So if "libskia.a" has included the functions as same as "lib/libwebp.a", maybe I can remove **"lib/libwebp.a** from the last link command's arguments list.
**What you should do just**:
1. follow the guideline of INSTALL.md until the "Multiple definition" Error occurs.
2. **Manually execute the failed subcommand(DO NOT FORGET to remove the "lib/libwebp.a" from the arguments)**, the example is (you should copy from your own error output of ninja build):
```
$ c++  -Wall -Wno-switch -O2 -g -DNDEBUG   src/CMakeFiles/aseprite.dir/main/main.cpp.o  -o bin/aseprite  lib/libapp-lib.a  lib/libclip.a  -lxcb  -lpthread  lib/libdio-lib.a  lib/libfilters-lib.a  lib/libflic-lib.a  lib/libtga-lib.a  lib/librender-lib.a  lib/libdoc-lib.a  lib/libfixmath-lib.a  lib/libui-lib.a  lib/liblaf-os.a  lib/liblaf-gfx.a  lib/liblaf-ft.a  /home/keval/Downloads/Skia-Linux-Release-x64/out/Release-x64/libskia.a  /usr/lib/libGL.so  /usr/lib/libfontconfig.so  /usr/lib/libSM.so  /usr/lib/libICE.so  /usr/lib/libX11.so  /usr/lib/libXext.so  /usr/lib/libXcursor.so  /home/keval/Downloads/Skia-Linux-Release-x64/out/Release-x64/libskshaper.a  lib/libobs.a  lib/libundo.a  lib/libcmark.a  lib/libjpeg.a  lib/libgiflib.a  lib/libwebpdemux.a  lib/libwebpmux.a  -lpthread  lib/libfreetype.a  lib/libharfbuzz.a  lib/libfreetype.a  lib/libharfbuzz.a  lib/libpng16.a  -lm  /usr/lib/libbz2.so  lib/libjson11.a  lib/libarchive.a  /usr/lib/liblz4.so  /usr/lib/libzstd.so  /usr/lib/libcrypto.so  /usr/lib/libexpat.so  /usr/lib/libacl.so  /usr/lib/libssl.so  lib/libfmt.a  lib/libtinyexpr.a  lib/liblauxlib.a  lib/liblua.a  lib/liblualib.a  lib/libupdater-lib.a  lib/libcfg-lib.a  lib/libver-lib.a  lib/libtinyxml.a  lib/libnet-lib.a  lib/liblaf-base.a  lib/libmodpbase64.a  /usr/lib/libdl.so  lib/libcurl.a  lib/libz.a  -ldl  -lidn  -lldap
```
At last, I got a usable Aseprite which still supprots WebP format picture.(I simply tested the webp-export and webp-open functions, they worked well)
This might help you. :-)

**Comment by asfaloth00** [comment] 2021-04-07 12:34
This is still happening, bump

**Comment by timjklein36** [comment] 2021-04-22 23:56
I am still seeing this issue as well, when building from latest `main` and using the prebuilt Skia release. @Aoczs' workaround was successful for me.

**Comment by Stereo528** [comment] 2021-05-03 05:38
Having this issue also, however, Aoczs' workaround was also successful for me.

**Comment by sergiendipia** [comment] 2021-05-04 12:17
As @Aoczs mentioned, executing the command but without lib/libwebp.a argument works as today.

**Comment by FalcoDJ** [comment] 2021-05-13 21:40
@Aoczs' solution worked for me too.

**Comment by rafahsena** [comment] 2021-05-19 17:20
@Aoczs  your solution worked for me, thanks.

**Comment by mohad12211** [comment] 2021-05-22 16:14
same issue here, Arch linux, @Aoczs's solution worked me

**Comment by MorticiaGrey** [comment] 2021-05-28 15:35
Same issue, Manjaro linux. @Aoczs's workaround worked

**Comment by dacap** [comment] 2021-05-28 16:36
I'll try to integrate the fix in CMake files (trying to use the libwebp from Skia when Skia is the configured back-end, and using the integrated libwebp when we compile the CLI-only version)

**Comment by Lepidopteran** [comment] 2021-05-28 21:50
@Aoczs workaround worked manjaro linux

**Comment by jusw85** [comment] 2021-05-29 04:42
Just to confirm, this only happens with pre-built skia right?

I don't have any issue if I compile skia with the instructions [here](https://github.com/aseprite/skia#skia-on-linux), then use that to build aseprite, on arch linux.

These are my cmake options
```
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -DLAF_BACKEND=skia \
        -DSKIA_DIR="$srcdir/skia" \
        -DSKIA_LIBRARY_DIR="$srcdir/skia/out/Clang" \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DUSE_SHARED_CMARK=ON \
        -DUSE_SHARED_CURL=ON \
        -DUSE_SHARED_JPEGLIB=ON \
        -DUSE_SHARED_GIFLIB=ON \
        -DUSE_SHARED_ZLIB=ON \
        -DUSE_SHARED_LIBPNG=ON \
        -DUSE_SHARED_TINYXML=ON \
        -DUSE_SHARED_PIXMAN=ON \
        -DUSE_SHARED_FREETYPE=ON \
        -DUSE_SHARED_HARFBUZZ=ON \
        -DWITH_WEBP_SUPPORT=ON \
        -DENABLE_TESTS=OFF \
        -DENABLE_BENCHMARKS=OFF \
        -DLAF_WITH_TESTS=OFF \
        -DLAF_WITH_EXAMPLES=OFF \
```

It includes webp support.

**Comment by sudoDavi** [comment] 2021-08-22 14:20
Same issue here, I just updated to Debian 11 and had a working copy of Aseprite v1.2.19, I tried compiling the latest release v1.2.28 and got the same conflict, I'm using the prebuilt skia library

**Comment by flamendless** [comment] 2021-09-11 06:41
> Just to confirm, this only happens with pre-built skia right?
> 
> I don't have any issue if I compile skia with the instructions [here](https://github.com/aseprite/skia#skia-on-linux), then use that to build aseprite, on arch linux.
> 
> These are my cmake options
> 
> ```
>         -DCMAKE_BUILD_TYPE=RelWithDebInfo \
>         -DLAF_BACKEND=skia \
>         -DSKIA_DIR="$srcdir/skia" \
>         -DSKIA_LIBRARY_DIR="$srcdir/skia/out/Clang" \
>         -DCMAKE_INSTALL_PREFIX=/usr \
>         -DUSE_SHARED_CMARK=ON \
>         -DUSE_SHARED_CURL=ON \
>         -DUSE_SHARED_JPEGLIB=ON \
>         -DUSE_SHARED_GIFLIB=ON \
>         -DUSE_SHARED_ZLIB=ON \
>         -DUSE_SHARED_LIBPNG=ON \
>         -DUSE_SHARED_TINYXML=ON \
>         -DUSE_SHARED_PIXMAN=ON \
>         -DUSE_SHARED_FREETYPE=ON \
>         -DUSE_SHARED_HARFBUZZ=ON \
>         -DWITH_WEBP_SUPPORT=ON \
>         -DENABLE_TESTS=OFF \
>         -DENABLE_BENCHMARKS=OFF \
>         -DLAF_WITH_TESTS=OFF \
>         -DLAF_WITH_EXAMPLES=OFF \
> ```
> 
> It includes webp support.

Im trying this but i get:
```
-- Extended attributes support: Linux
-- ACL support: libacl (POSIX.1e)
-- laf backend: skia
-- laf pixman: /usr/lib/libpixman-1.so
-- laf freetype: /usr/lib/libfreetype.so
-- laf harfbuzz: /usr/lib/libharfbuzz.so
-- skia dir: /home/brbl/Aseprite/skia
-- skia library: /home/brbl/Aseprite/skia/out/Release-x64/libskia.a
-- skia library dir: /home/brbl/Aseprite/skia/out/Release-x64
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CMARK_LIBRARIES
    linked by target "app-lib" in directory /home/brbl/Aseprite/aseprite-beta/src/app

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by flamendless** [comment] 2021-09-11 07:22
So compiling skia instead of using the prebuilt one works with the latest beta. Maybe there's something off with the one in the prebuilt one.

**Comment by Xtendera** [comment] 2022-10-24 18:46
Can be closed @dacap

**Comment by dacap** [comment] 2022-10-25 12:22
I think we can close this because we link with webp library from Skia now ccb32562ad7edfa992a8fb7fb4ce6c1bc4a216fc

**Closed by dacap** 2022-10-25 12:22 UTC
Labels: linux, compilation

**Comment by zhangguanzhang** [comment] 2024-05-30 01:53
```
LD_PRELOAD=xxx/libwebp.so.x bin_path
```
