### ISSUE TITLE
Failure while ninja aseprite

### ISSUE THREAD

**Issue by marroblop** [aseprite/aseprite#2773] opened 2021-06-15 15:34 UTC
When I run ninja aseprote i get this failure

FAILED: bin/aseprite 
: && /usr/bin/c++ -Wall -Wno-switch -O2 -g -DNDEBUG  src/CMakeFiles/aseprite.dir/main/main.cpp.o -o bin/aseprite  lib/libapp-lib.a  lib/libclip.a  -lxcb  -lpthread  lib/libdio-lib.a  lib/libfilters-lib.a  lib/libflic-lib.a  lib/libtga-lib.a  lib/librender-lib.a  lib/libdoc-lib.a  lib/libfixmath-lib.a  lib/libui-lib.a  lib/liblaf-os.a  lib/liblaf-gfx.a  lib/liblaf-ft.a  /home/charg3/deps/skia/out/Release-x64/libskia.a  /usr/lib/x86_64-linux-gnu/libGL.so  /usr/lib/x86_64-linux-gnu/libfontconfig.so  /usr/lib/x86_64-linux-gnu/libX11.so  /usr/lib/x86_64-linux-gnu/libXext.so  /usr/lib/x86_64-linux-gnu/libXcursor.so  /home/charg3/deps/skia/out/Release-x64/libskshaper.a  lib/libobs.a  lib/libundo.a  lib/libcmark.a  lib/libjpeg.a  lib/libgiflib.a  lib/libwebpdemux.a  lib/libwebpmux.a  lib/libwebp.a  -lpthread  -lm  lib/libfreetype.a  lib/libharfbuzz.a  lib/libfreetype.a  lib/libharfbuzz.a  lib/libpng16.a  -lm  lib/libjson11.a  lib/libarchive.a  /usr/lib/x86_64-linux-gnu/libexpat.so  lib/libfmt.a  lib/libtinyexpr.a  lib/liblauxlib.a  lib/liblua.a  lib/liblualib.a  lib/libupdater-lib.a  lib/libcfg-lib.a  lib/libver-lib.a  lib/libtinyxml.a  lib/libnet-lib.a  lib/liblaf-base.a  lib/libmodpbase64.a  /usr/lib/x86_64-linux-gnu/libdl.so  lib/libcurl.a  lib/libz.a  -ldl && :
/usr/bin/ld: lib/libwebp.a(alpha_processing.c.o): in function `WebPMultARGBRow_C':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/alpha_processing.c:140: multiple definition of `WebPMultARGBRow_C'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.alpha_processing.o):alpha_processing.c:(.text.WebPMultARGBRow_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(alpha_processing.c.o): in function `WebPMultRow_C':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/alpha_processing.c:161: multiple definition of `WebPMultRow_C'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.alpha_processing.o):alpha_processing.c:(.text.WebPMultRow_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(alpha_processing.c.o): in function `WebPMultARGBRows':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/alpha_processing.c:190: multiple definition of `WebPMultARGBRows'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.alpha_processing.o):alpha_processing.c:(.text.WebPMultARGBRows+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(alpha_processing.c.o): in function `WebPMultRows':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/alpha_processing.c:198: multiple definition of `WebPMultRows'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.alpha_processing.o):alpha_processing.c:(.text.WebPMultRows+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(alpha_processing.c.o): in function `WebPInitAlphaProcessing':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/alpha_processing.c:412: multiple definition of `WebPInitAlphaProcessing'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.alpha_processing.o):alpha_processing.c:(.text.WebPInitAlphaProcessing+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(dec.c.o): in function `VP8DspInit':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/dec.c:744: multiple definition of `VP8DspInit'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.dec.o):dec.c:(.text.VP8DspInit+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(filters.c.o): in function `VP8FiltersInit':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/filters.c:241: multiple definition of `VP8FiltersInit'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.filters.o):filters.c:(.text.VP8FiltersInit+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(lossless.c.o): in function `VP8LAddGreenToBlueAndRed_C':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/lossless.c:248: multiple definition of `VP8LAddGreenToBlueAndRed_C'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.lossless.o):lossless.c:(.text.VP8LAddGreenToBlueAndRed_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(lossless.c.o): in function `VP8LTransformColorInverse_C':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/lossless.c:276: multiple definition of `VP8LTransformColorInverse_C'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.lossless.o):lossless.c:(.text.VP8LTransformColorInverse_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(lossless.c.o): in function `VP8LConvertBGRAToRGB_C':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/lossless.c:432: multiple definition of `VP8LConvertBGRAToRGB_C'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.lossless.o):lossless.c:(.text.VP8LConvertBGRAToRGB_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(lossless.c.o): in function `VP8LConvertBGRAToRGBA_C':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/lossless.c:443: multiple definition of `VP8LConvertBGRAToRGBA_C'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.lossless.o):lossless.c:(.text.VP8LConvertBGRAToRGBA_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(lossless.c.o): in function `VP8LConvertBGRAToRGBA4444_C':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/lossless.c:455: multiple definition of `VP8LConvertBGRAToRGBA4444_C'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.lossless.o):lossless.c:(.text.VP8LConvertBGRAToRGBA4444_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(lossless.c.o): in function `VP8LConvertBGRAToRGB565_C':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/lossless.c:472: multiple definition of `VP8LConvertBGRAToRGB565_C'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.lossless.o):lossless.c:(.text.VP8LConvertBGRAToRGB565_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(lossless.c.o): in function `VP8LConvertBGRAToBGR_C':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/lossless.c:489: multiple definition of `VP8LConvertBGRAToBGR_C'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.lossless.o):lossless.c:(.text.VP8LConvertBGRAToBGR_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(lossless.c.o): in function `VP8LColorIndexInverseTransformAlpha':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/lossless.c:372: multiple definition of `VP8LColorIndexInverseTransformAlpha'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.lossless.o):lossless.c:(.text.VP8LColorIndexInverseTransformAlpha+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(lossless.c.o): in function `VP8LInverseTransform':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/lossless.c:379: multiple definition of `VP8LInverseTransform'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.lossless.o):lossless.c:(.text.VP8LInverseTransform+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(lossless.c.o): in function `VP8LConvertFromBGRA':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/lossless.c:514: multiple definition of `VP8LConvertFromBGRA'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.lossless.o):lossless.c:(.text.VP8LConvertFromBGRA+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(lossless.c.o): in function `VP8LDspInit':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/lossless.c:602: multiple definition of `VP8LDspInit'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.lossless.o):lossless.c:(.text.VP8LDspInit+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(rescaler.c.o): in function `WebPRescalerImportRowExpand_C':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/rescaler.c:30: multiple definition of `WebPRescalerImportRowExpand_C'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.rescaler.o):rescaler.c:(.text.WebPRescalerImportRowExpand_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(rescaler.c.o): in function `WebPRescalerImportRowShrink_C':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/rescaler.c:62: multiple definition of `WebPRescalerImportRowShrink_C'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.rescaler.o):rescaler.c:(.text.WebPRescalerImportRowShrink_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(rescaler.c.o): in function `WebPRescalerExportRowExpand_C':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/rescaler.c:108: multiple definition of `WebPRescalerExportRowExpand_C'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.rescaler.o):rescaler.c:(.text.WebPRescalerExportRowExpand_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(rescaler.c.o): in function `WebPRescalerExportRowShrink_C':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/rescaler.c:133: multiple definition of `WebPRescalerExportRowShrink_C'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.rescaler.o):rescaler.c:(.text.WebPRescalerExportRowShrink_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(rescaler.c.o): in function `WebPRescalerImportRow':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/rescaler.c:162: multiple definition of `WebPRescalerImportRow'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.rescaler.o):rescaler.c:(.text.WebPRescalerImportRow+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(rescaler.c.o): in function `WebPRescalerExportRow':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/rescaler.c:170: multiple definition of `WebPRescalerExportRow'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.rescaler.o):rescaler.c:(.text.WebPRescalerExportRow+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(rescaler.c.o): in function `WebPRescalerDspInit':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/rescaler.c:205: multiple definition of `WebPRescalerDspInit'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.rescaler.o):rescaler.c:(.text.WebPRescalerDspInit+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(upsampling.c.o): in function `WebPYuv444ToRgba4444_C':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/upsampling.c:195: multiple definition of `WebPYuv444ToRgba4444_C'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.upsampling.o):upsampling.c:(.text.WebPYuv444ToRgba4444_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(upsampling.c.o): in function `WebPYuv444ToRgb565_C':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/upsampling.c:196: multiple definition of `WebPYuv444ToRgb565_C'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.upsampling.o):upsampling.c:(.text.WebPYuv444ToRgb565_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(upsampling.c.o): in function `WebPYuv444ToBgr_C':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/upsampling.c:193: multiple definition of `WebPYuv444ToBgr_C'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.upsampling.o):upsampling.c:(.text.WebPYuv444ToBgr_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(upsampling.c.o): in function `WebPYuv444ToBgra_C':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/upsampling.c:190: multiple definition of `WebPYuv444ToBgra_C'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.upsampling.o):upsampling.c:(.text.WebPYuv444ToBgra_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(upsampling.c.o): in function `WebPYuv444ToRgb_C':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/upsampling.c:192: multiple definition of `WebPYuv444ToRgb_C'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.upsampling.o):upsampling.c:(.text.WebPYuv444ToRgb_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(upsampling.c.o): in function `WebPYuv444ToRgba_C':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/upsampling.c:189: multiple definition of `WebPYuv444ToRgba_C'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.upsampling.o):upsampling.c:(.text.WebPYuv444ToRgba_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(upsampling.c.o): in function `WebPYuv444ToArgb_C':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/upsampling.c:194: multiple definition of `WebPYuv444ToArgb_C'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.upsampling.o):upsampling.c:(.text.WebPYuv444ToArgb_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(upsampling.c.o): in function `WebPInitYUV444Converters':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/upsampling.c:222: multiple definition of `WebPInitYUV444Converters'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.upsampling.o):upsampling.c:(.text.WebPInitYUV444Converters+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(upsampling.c.o): in function `WebPInitUpsamplers':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/upsampling.c:263: multiple definition of `WebPInitUpsamplers'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.upsampling.o):upsampling.c:(.text.WebPInitUpsamplers+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(upsampling.c.o): in function `WebPGetLinePairConverter':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/upsampling.c:168: multiple definition of `WebPGetLinePairConverter'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.upsampling.o):upsampling.c:(.text.WebPGetLinePairConverter+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(yuv.c.o): in function `WebPConvertRGBA32ToUV_C':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/yuv.c:188: multiple definition of `WebPConvertRGBA32ToUV_C'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.yuv.o):yuv.c:(.text.WebPConvertRGBA32ToUV_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(yuv.c.o): in function `WebPConvertARGBToUV_C':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/yuv.c:129: multiple definition of `WebPConvertARGBToUV_C'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.yuv.o):yuv.c:(.text.WebPConvertARGBToUV_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(yuv.c.o): in function `WebPSamplerProcessPlane':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/yuv.c:55: multiple definition of `WebPSamplerProcessPlane'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.yuv.o):yuv.c:(.text.WebPSamplerProcessPlane+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(yuv.c.o): in function `WebPInitSamplers':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/yuv.c:78: multiple definition of `WebPInitSamplers'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.yuv.o):yuv.c:(.text.WebPInitSamplers+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(yuv.c.o): in function `WebPInitConvertARGBToYUV':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/yuv.c:263: multiple definition of `WebPInitConvertARGBToYUV'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.yuv.o):yuv.c:(.text.WebPInitConvertARGBToYUV+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(cost.c.o):/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/cost.c:18: multiple definition of `VP8EntropyCost'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.cost.o):(.rodata.VP8EntropyCost+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(cost.c.o):/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/cost.c:52: multiple definition of `VP8LevelFixedCosts'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.cost.o):(.rodata.VP8LevelFixedCosts+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(cost.c.o):/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/cost.c:314: multiple definition of `VP8EncBands'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.cost.o):(.rodata.VP8EncBands+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(cost.c.o): in function `VP8EncDspCostInit':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/cost.c:382: multiple definition of `VP8EncDspCostInit'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.cost.o):cost.c:(.text.VP8EncDspCostInit+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(enc.c.o): in function `VP8SetHistogramData':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/enc.c:47: multiple definition of `VP8SetHistogramData'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.enc.o):enc.c:(.text.VP8SetHistogramData+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(enc.c.o):/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/enc.c:34: multiple definition of `VP8DspScan'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.enc.o):(.rodata.VP8DspScan+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(enc.c.o): in function `VP8EncDspInit':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/enc.c:742: multiple definition of `VP8EncDspInit'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.enc.o):enc.c:(.text.VP8EncDspInit+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(lossless_enc.c.o): in function `VP8LSubtractGreenFromBlueAndRed_C':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/lossless_enc.c:505: multiple definition of `VP8LSubtractGreenFromBlueAndRed_C'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.lossless_enc.o):lossless_enc.c:(.text.VP8LSubtractGreenFromBlueAndRed_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(lossless_enc.c.o): in function `VP8LTransformColor_C':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/lossless_enc.c:525: multiple definition of `VP8LTransformColor_C'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.lossless_enc.o):lossless_enc.c:(.text.VP8LTransformColor_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(lossless_enc.c.o): in function `VP8LCollectColorRedTransforms_C':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/lossless_enc.c:562: multiple definition of `VP8LCollectColorRedTransforms_C'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.lossless_enc.o):lossless_enc.c:(.text.VP8LCollectColorRedTransforms_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(lossless_enc.c.o): in function `VP8LCollectColorBlueTransforms_C':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/lossless_enc.c:574: multiple definition of `VP8LCollectColorBlueTransforms_C'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.lossless_enc.o):lossless_enc.c:(.text.VP8LCollectColorBlueTransforms_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(lossless_enc.c.o): in function `VP8LBundleColorMap_C':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/lossless_enc.c:599: multiple definition of `VP8LBundleColorMap_C'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.lossless_enc.o):lossless_enc.c:(.text.VP8LBundleColorMap_C+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(lossless_enc.c.o):/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/lossless_enc.c:28: multiple definition of `kLog2Table'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.lossless_enc.o):(.rodata.kLog2Table+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(lossless_enc.c.o):/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/lossless_enc.c:159: multiple definition of `kSLog2Table'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.lossless_enc.o):(.rodata.kSLog2Table+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(lossless_enc.c.o): in function `VP8LBitEntropyInit':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/lossless_enc.c:409: multiple definition of `VP8LBitEntropyInit'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.lossless_enc.o):lossless_enc.c:(.text.VP8LBitEntropyInit+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(lossless_enc.c.o): in function `VP8LBitsEntropyUnrefined':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/lossless_enc.c:414: multiple definition of `VP8LBitsEntropyUnrefined'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.lossless_enc.o):lossless_enc.c:(.text.VP8LBitsEntropyUnrefined+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(lossless_enc.c.o): in function `VP8LHistogramAdd':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/lossless_enc.c:676: multiple definition of `VP8LHistogramAdd'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.lossless_enc.o):lossless_enc.c:(.text.VP8LHistogramAdd+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(lossless_enc.c.o): in function `VP8LEncDspInit':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/lossless_enc.c:901: multiple definition of `VP8LEncDspInit'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.lossless_enc.o):lossless_enc.c:(.text.VP8LEncDspInit+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(lossless_enc.c.o):/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/lossless_enc.c:293: multiple definition of `kPrefixEncodeExtraBitsValue'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.lossless_enc.o):(.rodata.kPrefixEncodeExtraBitsValue+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(lossless_enc.c.o):/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/lossless_enc.c:226: multiple definition of `kPrefixEncodeCode'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.lossless_enc.o):(.rodata.kPrefixEncodeCode+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(ssim.c.o): in function `SSIMCalculation':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/ssim.c:36: multiple definition of `VP8SSIMFromStats'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.ssim.o):ssim.c:(.text.VP8SSIMFromStats+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(ssim.c.o): in function `VP8SSIMFromStatsClipped':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/ssim.c:60: multiple definition of `VP8SSIMFromStatsClipped'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.ssim.o):ssim.c:(.text.VP8SSIMFromStatsClipped+0x0): first defined here
/usr/bin/ld: lib/libwebp.a(ssim.c.o): in function `VP8SSIMDspInit':
/home/charg3/aseprite/build/../third_party/libwebp/src/dsp/ssim.c:142: multiple definition of `VP8SSIMDspInit'; /home/charg3/deps/skia/out/Release-x64/libskia.a(libwebp.ssim.o):ssim.c:(.text.VP8SSIMDspInit+0x0): first defined here
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

### Aseprite and System version
* Aseprite version: 1.2.27 
* System: Sparky Linux

**Comment by mohad12211** [comment] 2021-06-15 23:19
possible duplicate of issue #2387 I think. the current fix is to run the failed subcommand without the `lib/libwebp.a` argument. so according to the output you posted, the command should be like this : 

`/usr/bin/c++ -Wall -Wno-switch -O2 -g -DNDEBUG src/CMakeFiles/aseprite.dir/main/main.cpp.o -o bin/aseprite lib/libapp-lib.a lib/libclip.a -lxcb -lpthread lib/libdio-lib.a lib/libfilters-lib.a lib/libflic-lib.a lib/libtga-lib.a lib/librender-lib.a lib/libdoc-lib.a lib/libfixmath-lib.a lib/libui-lib.a lib/liblaf-os.a lib/liblaf-gfx.a lib/liblaf-ft.a /home/charg3/deps/skia/out/Release-x64/libskia.a /usr/lib/x86_64-linux-gnu/libGL.so /usr/lib/x86_64-linux-gnu/libfontconfig.so /usr/lib/x86_64-linux-gnu/libX11.so /usr/lib/x86_64-linux-gnu/libXext.so /usr/lib/x86_64-linux-gnu/libXcursor.so /home/charg3/deps/skia/out/Release-x64/libskshaper.a lib/libobs.a lib/libundo.a lib/libcmark.a lib/libjpeg.a lib/libgiflib.a lib/libwebpdemux.a lib/libwebpmux.a -lpthread -lm lib/libfreetype.a lib/libharfbuzz.a lib/libfreetype.a lib/libharfbuzz.a lib/libpng16.a -lm lib/libjson11.a lib/libarchive.a /usr/lib/x86_64-linux-gnu/libexpat.so lib/libfmt.a lib/libtinyexpr.a lib/liblauxlib.a lib/liblua.a lib/liblualib.a lib/libupdater-lib.a lib/libcfg-lib.a lib/libver-lib.a lib/libtinyxml.a lib/libnet-lib.a lib/liblaf-base.a lib/libmodpbase64.a /usr/lib/x86_64-linux-gnu/libdl.so lib/libcurl.a lib/libz.a -ldl
`

but it's better to just copy the command after the `ninja aseprite` command fail, and remove this argument `lib/libwebp.a` and it should be solved

**Comment by marroblop** [comment] 2021-06-16 17:23
> possible duplicate of issue #2387 I think. the current fix is to run the failed subcommand manually without the `lib/libwebp.a` argument. so according to the output you posted, the command should be like this :
> 
> `/usr/bin/c++ -Wall -Wno-switch -O2 -g -DNDEBUG src/CMakeFiles/aseprite.dir/main/main.cpp.o -o bin/aseprite lib/libapp-lib.a lib/libclip.a -lxcb -lpthread lib/libdio-lib.a lib/libfilters-lib.a lib/libflic-lib.a lib/libtga-lib.a lib/librender-lib.a lib/libdoc-lib.a lib/libfixmath-lib.a lib/libui-lib.a lib/liblaf-os.a lib/liblaf-gfx.a lib/liblaf-ft.a /home/charg3/deps/skia/out/Release-x64/libskia.a /usr/lib/x86_64-linux-gnu/libGL.so /usr/lib/x86_64-linux-gnu/libfontconfig.so /usr/lib/x86_64-linux-gnu/libX11.so /usr/lib/x86_64-linux-gnu/libXext.so /usr/lib/x86_64-linux-gnu/libXcursor.so /home/charg3/deps/skia/out/Release-x64/libskshaper.a lib/libobs.a lib/libundo.a lib/libcmark.a lib/libjpeg.a lib/libgiflib.a lib/libwebpdemux.a lib/libwebpmux.a -lpthread -lm lib/libfreetype.a lib/libharfbuzz.a lib/libfreetype.a lib/libharfbuzz.a lib/libpng16.a -lm lib/libjson11.a lib/libarchive.a /usr/lib/x86_64-linux-gnu/libexpat.so lib/libfmt.a lib/libtinyexpr.a lib/liblauxlib.a lib/liblua.a lib/liblualib.a lib/libupdater-lib.a lib/libcfg-lib.a lib/libver-lib.a lib/libtinyxml.a lib/libnet-lib.a lib/liblaf-base.a lib/libmodpbase64.a /usr/lib/x86_64-linux-gnu/libdl.so lib/libcurl.a lib/libz.a -ldl `
> 
> but it's better to just copy the command from your terminal after the `ninja aseprite` command fail, remove this argument `lib/libwebp.a` and execute it again and it should be solved.

The command ran fine but the aseprite file in home/aseprite/build/bin doesnt open or is shown as a executable program file.

**Closed** 2021-06-23 11:57 UTC
Labels: compilation, duplicate
