### ISSUE TITLE
Preview window glitched

### ISSUE THREAD

**Issue by sarcasmloading** [aseprite/aseprite#1027] opened 2016-03-23 07:38 UTC
The Aseprite v1.1.3 (compiled) preview thing when moved lags. Like this (http://i.stack.imgur.com/BJGBH.png)

I did the compile process again to no avail.

_OS: Windows 10 Professional 64-bit
Compiled with VS 2015
Version is v1.1.3-dev_

**Comment by sirblackheart** [comment] 2016-03-23 09:39
probably duplicate of #1006

**Closed** 2016-03-23 12:25 UTC
Labels: duplicate
