### ISSUE TITLE
Bug: Moving preview window around laggy, rendering issues (Linux)

### ISSUE THREAD

**Issue by arcooke** [aseprite/aseprite#1006] opened 2016-03-09 07:28 UTC
Best explained with a video: https://www.youtube.com/watch?v=kKWBo3wztq0

Not a major issue, but it puts a heavy load on the CPU.  Feels like I'm winning a game of Solitaire every time I move the window, can't complain.

I'm using 1.1.3 on Linux Mint

**Comment by dacap** [comment] 2016-03-09 16:38
:open_mouth: it happens on Windows too. I'll fix this ASAP

> Feels like I'm winning a game of Solitaire every time I move the window, can't complain.

:smile:

**Comment by dacap** [comment] 2016-03-09 16:42
Anyway it behaves randomly. Sometimes it happens and other times it doesn't happen.

**Comment by allkhor** [comment] 2016-04-07 17:04
Confirmed on Ubuntu 14.04 x64. Moving canvas very laggy too and makes high cpu usage. It's happened only if i used mouse, when used wacom pen Aseprite work correct.

**Comment by dacap** [comment] 2016-04-07 18:04
Hi @allkhor, are you using the official release? or a compiled one?

**Comment by allkhor** [comment] 2016-04-07 18:12
Hello @dacap, im compile current master branch, CMAKE_BUILD_TYPE:STRING=Release, and upstream curl branch. Aseprite 1.1.2 work good.

**Comment by dacap** [comment] 2016-04-07 18:16
Has your mouse high resolution? (I'm trying to understand why moving the canvas is slow with the mouse but not with the wacom pen)

**Comment by allkhor** [comment] 2016-04-07 18:23
I have logitech g600 (200 - 8200dpi) when i change dpi(hardware) no affect here.

**Comment by allkhor** [comment] 2016-04-07 18:44
Maybe it happens because mouse has 1000Hz polling rate and  the wacom table has a lower polling rate?

**Comment by geckojsc** [comment] 2016-04-09 14:01
This seems to happen pretty consistently for me on Windows, regardless of UI scale or anything, and for every window (not just the preview window). The faster I move the mouse, the worse it happens.

It becomes less severe if I make the Aseprite window smaller, but CPU usage is still high while dragging. It occurs when I resize windows too, however it *doesn't* occur when I resize the palette or any other split-panel.

Sorry I can't be of more help. I'm on a recent master build.

**Comment by allkhor** [comment] 2016-04-10 16:25
Some info: I compiled version 1.1.3 of the release, the current master branch not compile on Windows, compile gives a lot of errors.
 
Changing the dpi 200-8200 has no effect. As I said the problem starts to occur when the mouse polling rate is greater than 250hz(reports / sec). My mouse can dynamicly change polling rate between 125-1000hz. 

Lag higher with: screen scaling 100%, ui element scaling 200%. When i set 1000hz(modern mouse default) i have mouse freezes, very laggy, but 125Hz all good.

Moving preview windows laggy all time.

**Comment by dacap** [comment] 2016-04-10 19:02
The rendering issues should be related to this commit https://github.com/aseprite/aseprite/commit/1588e834c3838ffda630abc21bb70c2d4fd75d4d
specifically these lines:
https://github.com/aseprite/aseprite/commit/1588e834c3838ffda630abc21bb70c2d4fd75d4d#diff-fa5a5001ac6008c80a38b2326237bfe8R624
and
https://github.com/aseprite/aseprite/commit/1588e834c3838ffda630abc21bb70c2d4fd75d4d#diff-fa5a5001ac6008c80a38b2326237bfe8R1467

When a widget is moved, its position (bounds) change, so paint messages in the queue are invalid and they're removed. It means that if we flood the message queue with mouse messages, paint messages aren't processed because they are invalidated by mouse messages. It was done to fix scrolling issues in the sprite editor/scrollable widgets (to blit/move/re-use still valid screen regions).

I'll see how to fix this issue, maybe window movement and splitters should flush drawing messages to update the screen as fast as possible.

**Comment by dacap** [comment] 2016-04-12 20:06
@geckojsc Could you please give a try to this issue on Windows with the new v1.1.4 release (the official one, which is compiled with Skia)?

**Comment by geckojsc** [comment] 2016-04-12 22:31
@dacap yeah, it appears to be fixed now! Finally decided to buy on itch.io. Compared to Aseprite-old-backend.exe which was included in the installer, the CPU and memory usage of the new build are both generally improved. This also fixed #1051 for me :)

**Comment by dacap** [comment] 2016-04-12 23:06
@geckojsc glad to hear that Jeremy! And thanks for your support :beers:

This issue should be fixed when the Skia port is ready for Linux.

**Comment by HansLehnert** [comment] 2016-05-09 23:11
Wanted to point out I'm getting this issue on Windows 10 running current master branch compilation.

![gif](https://cloud.githubusercontent.com/assets/19274477/15130886/2127fc22-1622-11e6-8a1c-f486f81047ee.gif)

**Comment by dacap** [comment] 2016-05-09 23:52
Hi @HansLehnert, could you give a try to the Skia back-end? It should fix the issue. (See instructions INSTALL.md about how to compile Aseprite with the Skia back-end.)

**Comment by HansLehnert** [comment] 2016-05-12 01:10
Yes, that fixed it. Thanks

**Comment by dacap** [comment] 2017-01-06 19:24
eb0f046dc7f975fae6922daf2e7b6d5e3ed62c58 has fixed some UI problems, and also reduced this issue a little, anyway still visible on Alleg/Linux port

**Closed** 2018-08-16 18:47 UTC
Labels: bug, critical, linux
