### ISSUE TITLE
[Wayland] Implement IME support.

### ISSUE THREAD

**Issue by MicroGame0** [aseprite/aseprite#4538] opened 2024-06-16 11:59 UTC
Describe your bug report or feature request here
...
...
...

### Aseprite and System version

* Aseprite version: dev
* System: Linux

**Comment by dacap** [comment] 2024-06-16 12:05
Duplicate of #2841, anyway Wayland is low priority for us (the list of implementations go as Windows > macOS > X11 and finally Wayland if needed)

**Closed** 2024-06-16 12:05 UTC
Labels: duplicate
