### ISSUE TITLE
Opacity 255 in Alpha Compositing to Behave as Simple Ink

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#3047] opened 2021-11-10 10:57 UTC
Open this file: 
![ninja_bg_index alternate 2](https://user-images.githubusercontent.com/8582123/141088093-68f6e423-fd7b-4630-aeb3-c1a1022954a2.png)
Eyedrop the black in the top left corner of the image in color+alpha mode. Index 15 is selected.
Click index 0 in the palette to select it as the foreground color.
Fill the black in the top left corner of the image with the foreground color with Alpha Compositing ink and alpha 255.
Eyedrop the black in the top left corner of the image. Index 15 is still selected. The expectation was for it to be filled with the same color index.
GIF of this case:
![Aseprite Palette Fill Issue](https://user-images.githubusercontent.com/8582123/141089017-1a278947-15c6-4584-877d-e70c3ffa12e5.gif)

Aseprite 1.3-beta7-x64 Steam
Windows 10

It works as expected in Aseprite 1.2.30-x64 Steam on Windows 10.
It also works as expected with the other blacks in the palette that are not index 0 in Aseprite 1.3-beta7-x64 Steam
I understand the need to color match after compositing for semi transparent brush colors, but this current behavior confused me

**Comment by iamOgunyinka** [comment] 2022-02-10 16:41
Note to self: the reason this works in `main` and not in `beta` is due to the difference in the result returned by the ink's [`RgbMap::mapColor()`](https://github.com/aseprite/aseprite/blob/845ff177880822f33939cfbe58ca5bebaf4efbea/src/app/tools/ink_processing.h#L295). The `beta` branch uses a new overload, more investigation into the octree.

**Comment by iamOgunyinka** [comment] 2022-02-14 11:04
@dacap I want to ask you about this behavior. In this screenshot I attached, there is a palette that has seven (7) identical colors at different indexes `[0, 4, 8, 12, 13, 14, 15]`. When we [add these colors to the octree map](https://github.com/aseprite/aseprite/blob/8b5133b4c03ea3789da0b628fce738f635df65b7/src/doc/octree_map.cpp#L32), using their [indexes in the palette](https://github.com/aseprite/aseprite/blob/8b5133b4c03ea3789da0b628fce738f635df65b7/src/doc/octree_map.cpp#L350-L356) as the `paletteIndex`, new values overwrite the old values, as expected in any typical map.

```
// color 4278190080 is the color of interest here, so the octree map uses a function to calculate the index of the color.

int index = getHextet(4278190080, level);      // almost always yield `8` for levels in [0,8).
```

So we now have the following sequence:

```
a[8] = 0;
a[8] = 4;
a[8] = 8;
a[8] = 12;
a[8] = 13;
a[8] = 14;
a[8] = 15;
```
Of course, the last value is the only value that'd be retained in the map. So when we try to paint a region on the sprite with the first color in the palette, using the [TransparentInkProcessing\<IndexedTraits\>](https://github.com/aseprite/aseprite/blob/8b5133b4c03ea3789da0b628fce738f635df65b7/src/app/tools/ink_processing.h#L295), what we end up using is the _color_ at index 15. So the Eyedrop's behavior is correct.

![image](https://user-images.githubusercontent.com/4146085/153847827-0517a397-bbd1-4510-9bfb-558081efd53f.png)

My question: is this a bug or the expected behavior? I can't tell which it is.

**Comment by dacap** [comment] 2022-02-14 13:16
> is this a bug or the expected behavior?

@iamOgunyinka I would say that this is a bug. In transparent layers we could expect to map RGBA=0,0,0,255 to the first match in the palette instead of the last one, e.g. in the original example it's 0 for background layers, and index 4 for transparent layers (but never entry 15 as there are other colors in the palette that matches first).

Anyway the "Alpha Compositing" is a little strange in indexed mode, I think that if there is no alpha composition involved (all opacity is 255), and the active color is index, it should just paint the selected index color (so if we have index 15 selected with "Alpha Compositing", it should paint with index 15, not with 0 or 4, this means that we should use just `CopyInkProcesing`, maybe something to fix [here](https://github.com/aseprite/aseprite/blob/8b5133b4c03ea3789da0b628fce738f635df65b7/src/app/tools/inks.h#L146)).

About the generation of the octree [here](https://github.com/aseprite/aseprite/blob/8b5133b4c03ea3789da0b628fce738f635df65b7/src/doc/octree_map.cpp#L350-L356), probably changing the order at which palette indexes are processed might fix part of the problem:

```c++
  for (int i=palette->size()-1; i>=0; i--) {
    if (i == maskIndex) {
      m_root.addColor(palette->entry(i), 0, &m_root, maskColorBestFitIndex, 8);
      continue;
    }
    m_root.addColor(palette->entry(i), 0, &m_root, i, 8);
  }
```

Maybe @Gasparoken can say something about it.

---

@KasumiArai about this case, you can workaround the issue using the old (v1.2) RGB color mapping instead of octree:

<img width="816" alt="Screen Shot 2022-02-14 at 10 01 14" src="https://user-images.githubusercontent.com/39654/153870512-7482a5b0-65e4-438a-a110-03ad293d51fc.png">

**Comment by Gasparoken** [comment] 2022-02-15 03:26
> Anyway the "Alpha Compositing" is a little strange in indexed mode, I think that if there is no alpha composition involved (all opacity is 255), and the active color is index, it should just paint the selected index color (so if we have index 15 selected with "Alpha Compositing", it should paint with index 15, not with 0 or 4, this means that we should use just `CopyInkProcesing`, maybe something to fix [here](https://github.com/aseprite/aseprite/blob/8b5133b4c03ea3789da0b628fce738f635df65b7/src/app/tools/inks.h#L146)).

`Alpha Compositing` has the feature of compositing the color in the sprite with the current selected fg color, then the resulting color is searched through the palette to find the best fit (this search occurs only in Indexed Color Mode).

For example, assume a sprite in Indexed Color Mode with a Background layer, and it has a palette with white as 'transparent' index, green, dark green and semitransparent black:

![153892284-a06dea51-b84d-4249-a5ca-c98762e69790](https://user-images.githubusercontent.com/32165475/153958093-83f97182-bffb-4d1d-80d9-89be12205d52.png)

In ink type = 'Alpha Compositing', If you pick semitransparent black and try painting over a green pixel, it'll result DARK GREEN (i.e. the better color index which RGB is near to the composition of green + semitransparent black).

On the other hand, in ink type = `Simple`, If you pick semitransparent black and try painting over any color, it'll result in the composition of TRANSPARENT INDEX (white in this case) +  semitransparent black = gray.

![153896127-ff86320d-da42-4d47-979f-9ad2ed2a4154](https://user-images.githubusercontent.com/32165475/153957938-2cfa8cf3-d1d7-4c90-8f3c-e7d5a295bf71.png)

I saw when we painting with the Transparent Index color in `Alpha Compositing` we turn true 'opaque' variable [here](https://github.com/aseprite/aseprite/blob/8b5133b4c03ea3789da0b628fce738f635df65b7/src/app/tools/inks.h#L151) and that's why Transparent Processing is selected [here](https://github.com/aseprite/aseprite/blob/8b5133b4c03ea3789da0b628fce738f635df65b7/src/app/tools/inks.h#L165) and finally, the 'pre-composition' is done [here](https://github.com/aseprite/aseprite/blob/8b5133b4c03ea3789da0b628fce738f635df65b7/src/app/tools/ink_processing.h#L295)

I'm testing this change (but `inks.lua` test is failing so, I need to do a little more research on it):

<img width="1039" alt="Screen Shot 2022-02-15 at 00 21 45" src="https://user-images.githubusercontent.com/32165475/153986744-bbb4500d-0b5b-47e6-bbee-b1b4f826cfac.png">


I'll review octree scheme too (tomorrow).

**Comment by dacap** [comment] 2022-03-02 19:14
I'm closing this issue but I think still some work to add colors in the octree in reverse order should be done.

**Closed by dacap** 2022-03-02 19:14 UTC
Labels: bug, colorbar, time-3
