### ISSUE TITLE
Ctrl Key mysteriously not working on a German keyboard

### ISSUE THREAD

**Issue by lightofanima** [aseprite/aseprite#1144] opened 2016-05-22 12:40 UTC
My laptop has a German keyboard, though I use an English(UK) layout.

Aseprite used to work fine, but at some point the Ctrl, Alt and Shift keys stopped working. I could no longer undo/redo, etc. using my keyboard. Normal keys still worked, so if I pressed "Ctrl+Z" Aseprite behaved as if I pressed "Z".

On my keyboard, the Ctrl key is labelled as Strg. So I have replaced all instances of "Ctrl+" with "Strg+" in gui.xml. This fixed the issue for the Ctrl key.

OS: Windows 10
Occurs On: Aseprite 9.5 (precompiled downloadable version), latest version compiled from source

Not sure how important this is since it doesn't seem like many people are having this problem, but thought I should report it :) This occurs only on Aseprite and all other applications work fine.

**Comment by x421** [comment] 2016-10-09 11:10
Not sure how this is related, but I got a similiar effect:
The OS is Windows 10 too and I am also using the german keyboard layout.

After some time (was not able to reproduce the exact moment yet) all keys stop working here. Built it myselft on the master yesterday (1.1.9-dev, with allegro).

So even bindings like "b" for the pencil tool can not be used anymore.

**Comment by dacap** [comment] 2016-11-17 16:21
The next official release (v1.1.10, skia back-end) should not have this issue.

I'll close this issue because it's related to the deprecated Allegro back-end (v0.9.5, or v1.1.9-dev with Allegro)

**Closed by dacap** 2016-11-17 16:21 UTC
Labels: bug, keyboard
