### ISSUE TITLE
Bug: Preview in color curve update

### ISSUE THREAD

**Issue by Cerno-b** [aseprite/aseprite#983] opened 2016-02-27 20:57 UTC
Minor issue: The color curve modifications do not update when the preview checkbox is selected.

Steps to reproduce:
- Open color curve dialog
- Change the color curve
- Activate the preview checkbox --> Color changes do not appear in the drawing pane.
- Change the color curve again with preview enabled --> Now it updates correctly.

Also I don't know if that is intentional, but the preview does not affect the preview window (F7) at all. It is only shown on the working image.

**Comment by dacap** [comment] 2016-06-13 15:33
Hi @Cerno-b, it looks like color curve modifications are not updated when the preview checkbox is deactivated. But it seems to work when it's actived:

![color-curve-preview](https://cloud.githubusercontent.com/assets/39654/16013196/edce7d54-3162-11e6-82e5-426f13e6b50c.gif)

**Comment by dacap** [comment] 2016-07-25 14:44
I'm closing this issue because I wasn't able to reproduce it with those specific steps.

**Closed by dacap** 2016-07-25 14:44 UTC
Labels: bug
