### ISSUE TITLE
Problem with "frameTags" output when exporting an individual layer

### ISSUE THREAD

**Issue by Cardinal90** [aseprite/aseprite#2116] opened 2019-07-24 22:39 UTC
Hello,

This is my timeline
![e05ccb15c391443e01ac5218960eb784](https://user-images.githubusercontent.com/11640898/61832732-bc4e4500-ae7a-11e9-9864-56dccfd43a8a.png)

[Here is an .aseprite file](https://github.com/aseprite/aseprite/files/3428979/basic-door.zip)

I am exporting the "door-cover" layer with this command:
`aseprite.exe -b --layer "door-cover" basic-door.aseprite --trim --sheet-pack --sheet door-cover.png --format json-array --list-tags --data door-cover.json`

Here is the result:
```json
{ "frames": [
   {
    "filename": "basic-door (door-cover) 3.aseprite",
    "frame": { "x": 0, "y": 80, "w": 96, "h": 41 },
    "rotated": false,
    "trimmed": true,
    "spriteSourceSize": { "x": 0, "y": 5, "w": 96, "h": 41 },
    "sourceSize": { "w": 96, "h": 96 },
    "duration": 80
   },
   {
    "filename": "basic-door (door-cover) 13.aseprite",
    "frame": { "x": 0, "y": 0, "w": 96, "h": 80 },
    "rotated": false,
    "trimmed": true,
    "spriteSourceSize": { "x": 0, "y": 5, "w": 96, "h": 80 },
    "sourceSize": { "w": 96, "h": 96 },
    "duration": 80
   }
 ],
 "meta": {
  "app": "http://www.aseprite.org/",
  "version": "1.2.13-x64",
  "image": "door-cover.png",
  "format": "RGBA8888",
  "size": { "w": 128, "h": 128 },
  "scale": "1",
  "frameTags": [
   { "name": "Up-closed", "from": 0, "to": 0, "direction": "forward" },
   { "name": "Up-opening", "from": 1, "to": 1, "direction": "forward" },
   { "name": "Up-closing", "from": 2, "to": 2, "direction": "forward" },
   { "name": "Up-opened", "from": 3, "to": 3, "direction": "forward" },
   { "name": "Down-partial", "from": 4, "to": 4, "direction": "forward" },
   { "name": "Down-reveal", "from": 5, "to": 12, "direction": "forward" },
   { "name": "Down-opened", "from": 13, "to": 13, "direction": "forward" }
  ]
 }
}
```

I am not sure if this behavior is intended. I expected to see either a number of empty frames (considering I don't use `--ignore-empty`) or `frameTags` having valid `from` and `to` fields. As it stands, `frameTags` output is absolutely useless. Is it possible to fix it?

### Aseprite and System version

* Aseprite version: 1.2.13, Steam
* System: Windows 10 x64

**Comment by dacap** [comment] 2019-07-31 18:23
Thanks for reporting this @Cardinal90, I'll try to prepare a fix for the next version. I think the problem is that `--trim` is removing frames from the final result, and then `frameTags` is not updated properly to reflect that.

**Comment by dacap** [comment] 2019-10-01 23:38
Finally, this will be fixed adding empty frames to fill the items of the JSON array with empty frames (if `-ignore-empty` is specified, those empty frames will be removed). Also we'll try to remove duplicate entries in the `.png` output with `-sheet-pack` so space is not wasted.

**Closed** 2019-10-01 23:45 UTC
Labels: bug, cli, critical priority
