### ISSUE TITLE
Issue with Exporting

### ISSUE THREAD

**Issue by flamendless** [aseprite/aseprite#1900] opened 2018-10-16 10:59 UTC
Hi, here's the case:
If i have a single .asefile which contains many tags, then I exported each tag, along with json, the output json file still has the other `frameTags` there and the `to` and `from` values are not properly set.

example:
1. tag `idle` has 4 frames, from 1 to 4.
2. tag `jump` has 2 frames, from 5 to 6.

The exported json for jump should have `from` 1 and `to` 6. And must not contain info about the `idle` frameTag.

This is needed for third-party lib/modules we use in utilizing aseprite, like [here](https://github.com/josh-perry/peachy)

### Aseprite and System version

* Aseprite version: 1.3-dev, built from source
* System: Linux 4.14 - Manjaro i3wm

**Comment by dacap** [comment] 2018-10-25 15:01
I think this is a duplicate of #1889

**Closed by dacap** 2018-10-25 15:01 UTC
Labels: duplicate
