### ISSUE TITLE
Stuck with eyedropper tool

### ISSUE THREAD

**Issue by paulguy** [aseprite/aseprite#1137] opened 2016-05-19 02:52 UTC
I don't know if this was just me not getting something or what but I was randomly stuck with the eyedropper tool and I could not select any other tools.  The buttons for those tools wouldn't even select.  There didn't seem to be any real reason for this where I was expected to do something in response to something I did or anything like that.  I had been messing with some layers and had recently deleted an animation frame.  That's all I can really guess.  Version was 1.1.5.4 acquired from Steam in Linux.

**Comment by dacap** [comment] 2016-05-19 12:10
Hi @paulguy, next time you got stuck with the eyedropper tool, please try to press and release the `Alt` key, I suspect that it might be the cause (i.e. the program never received an event that the `Alt` key was released).

**Comment by paulguy** [comment] 2016-05-19 12:34
Ah, see, I figured it may have been something like that, but I didn't know what key it could be.  I'll try that next time if it happens again.

**Comment by dacap** [comment] 2016-05-24 15:56
Note: this issue should be fixed with the new back-end on Linux #139

**Comment by dacap** [comment] 2016-11-17 16:19
On other platforms (e.g. Windows), this can happen if we assign a key like ` as a shortcut for eyedropper (quick).

**Comment by Metajake** [comment] 2017-09-13 18:45
I am getting the same issue. Aseprite seems to get stuck on the Eyedropper when I switch between programs, or wake up from sleep. I have tried all of the "hold alt" solutions, but they are not working. Usually I restart the program to return to normal, but one time I just switched programs again, and returning to Aseprite fixed the tool.
Mac Sierra OS, Aseprite v1.1.13

**Comment by dacap** [comment] 2024-04-08 15:48
The Linux bug might be fixed in https://github.com/aseprite/aseprite/issues/4368 with https://github.com/aseprite/laf/commit/c0c88e397a6c7dcdc78f0f67ee8bdb8e0d0760c5

**Closed by dacap** 2024-04-08 15:48 UTC
Labels: bug, linux, keyboard
