### ISSUE TITLE
Colors appear slighty transparent no matter the alpha

### ISSUE THREAD

**Issue by nekonesse** [aseprite/aseprite#2691] opened 2021-04-04 18:08 UTC
So when trying to override a color with another one. it appears like its slighty transparent/blending, even if the alpha is 255, 
and it gets annoying because if it generates a lot of shades of colors overtime and its just weird, it just started happening earlier this year.
![image](https://user-images.githubusercontent.com/50628290/113517619-0ee86b80-954f-11eb-9a9c-1a0f2876fe59.png)
in this image, i put a dark square in the corner, and then put a lighter color over the entire canvas, and if you look on the other half the red is on, theres a slightly darker color than the rest of the light color on the canvas, and of course this only works on RGB mode, so with indexed it works like intended.

### Aseprite and System version

* Aseprite version: 1.2.25, Steam
* System: Windows

**Comment by Gasparoken** [comment] 2021-11-17 14:06
Thanks for this report CGGSqaure. I tried to reproduce this issue (on 1.2.30), but I don't sure if I'm doing as you said.
When you said: "....and then put a lighter color over the entire canvas...." did you mean: "...and then painted the remain with Paint Bucket tool with other color..." or in other layer behind, did you painted the entire canvas with gray color?
I tried both and I don't the way to reproduce it.

**Comment by CGGSqaure** [comment] 2021-11-17 19:25
honestly, i tried to reproduce this issue because i think i already solved it by turning off some "blend colors" mode a while back, but now i cant even seem to figure out what did it in the first place. i have the 1.3 beta 7, so. i guess either it was indeed a bug and was fixed or something or im just dumb and cant remember

**Comment by Gasparoken** [comment] 2021-11-25 17:30
No problem! And thank you again!
Now I'm closing this issue. Anyway, if you find how to reproduce it, you can email us to support@aseprite.org to re-open it.

**Closed** 2021-11-25 17:30 UTC
Labels: bug, we cannot reproduce it
