### ISSUE TITLE
building v1.3-beta14 on apple m1 with latest skia(m102) fails, works with previous(m96) though

### ISSUE THREAD

**Issue by jsomedon** [aseprite/aseprite#3282] opened 2022-05-11 07:35 UTC
Building v1.3-beta14 with skia m102 fails, but m96 works. I am building on Apple silicon. Note that I am building with [`ENABLE_LIBB2:BOOL` off as mentioned in this issue](https://github.com/aseprite/aseprite/issues/3257#issuecomment-1101699826). (Leaving it on still gives the same build error mentioned in that issue)

here is error message:
```
FAILED: laf/os/CMakeFiles/laf-os.dir/skia/skia_color_space.cpp.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DCMARK_STATIC_DEFINE -DGR_GL_FUNCTION_TYPE=__stdcall -DHAVE_CONFIG_H -DHAVE_CONFIG_OVERRIDE_H=1 -DLAF_FREETYPE -DLAF_MACOS -DLAF_SKIA -DLAF_WITH_REGION -DNDEBUG -DPNG_NO_MMX_CODE -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DSK_BUILD_FOR_MAC -DSK_FORCE_DISTANCE_FIELD_TEXT=0 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_SRGB -DSK_INTERNAL -DSK_SCALAR_TO_FLOAT_EXCLUDED -DSK_SUPPORT_GPU=0 -DSK_SUPPORT_OPENCL=0 -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/third_party/zlib -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/build/third_party/zlib -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/third_party/libpng -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/build/third_party/libpng -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/third_party/libwebp/src -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/third_party/tinyxml -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/third_party/pixman/pixman -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/build -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/third_party/giflib -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/third_party/jpeg -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/third_party/curl/include -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/third_party/simpleini -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/build/laf -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/src -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/third_party/stringencoders/src -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/third_party/externals/freetype/include -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/third_party/externals/harfbuzz/src -stdlib=libc++ -O2 -g -DNDEBUG -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -mmacosx-version-min=11.0   -Wno-c++14-extensions -Wno-ignored-attributes -Wno-unused-result -Wno-deprecated-declarations -Werror=inconsistent-missing-override -fobjc-arc -std=c++14 -MD -MT laf/os/CMakeFiles/laf-os.dir/skia/skia_color_space.cpp.o -MF laf/os/CMakeFiles/laf-os.dir/skia/skia_color_space.cpp.o.d -o laf/os/CMakeFiles/laf-os.dir/skia/skia_color_space.cpp.o -c /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/skia_color_space.cpp
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/skia_color_space.cpp:16:
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/include/core/SkString.h:15:
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/include/private/SkTArray.h:15:
/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/include/private/SkTLogic.h:54:67: error: no member named 'size' in namespace 'std'
constexpr int SkCount(const Container& c) { return SkTo<int>(std::size(c)); }
                                                             ~~~~~^
1 error generated.

FAILED: laf/os/CMakeFiles/laf-os.dir/skia/os.cpp.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DCMARK_STATIC_DEFINE -DGR_GL_FUNCTION_TYPE=__stdcall -DHAVE_CONFIG_H -DHAVE_CONFIG_OVERRIDE_H=1 -DLAF_FREETYPE -DLAF_MACOS -DLAF_SKIA -DLAF_WITH_REGION -DNDEBUG -DPNG_NO_MMX_CODE -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DSK_BUILD_FOR_MAC -DSK_FORCE_DISTANCE_FIELD_TEXT=0 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_SRGB -DSK_INTERNAL -DSK_SCALAR_TO_FLOAT_EXCLUDED -DSK_SUPPORT_GPU=0 -DSK_SUPPORT_OPENCL=0 -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/third_party/zlib -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/build/third_party/zlib -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/third_party/libpng -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/build/third_party/libpng -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/third_party/libwebp/src -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/third_party/tinyxml -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/third_party/pixman/pixman -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/build -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/third_party/giflib -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/third_party/jpeg -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/third_party/curl/include -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/third_party/simpleini -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/build/laf -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/src -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/third_party/stringencoders/src -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/third_party/externals/freetype/include -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/third_party/externals/harfbuzz/src -stdlib=libc++ -O2 -g -DNDEBUG -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -mmacosx-version-min=11.0   -Wno-c++14-extensions -Wno-ignored-attributes -Wno-unused-result -Wno-deprecated-declarations -Werror=inconsistent-missing-override -fobjc-arc -std=c++14 -MD -MT laf/os/CMakeFiles/laf-os.dir/skia/os.cpp.o -MF laf/os/CMakeFiles/laf-os.dir/skia/os.cpp.o.d -o laf/os/CMakeFiles/laf-os.dir/skia/os.cpp.o -c /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/os.cpp
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/os.cpp:12:
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/skia_system.h:16:
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/skia_font_manager.h:16:
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/include/core/SkString.h:15:
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/include/private/SkTArray.h:15:
/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/include/private/SkTLogic.h:54:67: error: no member named 'size' in namespace 'std'
constexpr int SkCount(const Container& c) { return SkTo<int>(std::size(c)); }
                                                             ~~~~~^
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/os.cpp:12:
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/skia_system.h:17:
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/skia_surface.h:19:
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/skia_helpers.h:17:
/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/include/core/SkPaint.h:474:10: error: no template named 'optional' in namespace 'std'
    std::optional<SkBlendMode> asBlendMode() const;
    ~~~~~^
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/os.cpp:12:
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/skia_system.h:17:
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/skia_surface.h:22:
/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/include/core/SkCanvas.h:69:16: warning: nested namespace definition is a C++17 extension; define each namespace separately [-Wc++17-extensions]
namespace skgpu::graphite { class Recorder; }
               ^~~~~~~~~~
                { namespace graphite        } 
/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/include/core/SkCanvas.h:2303:10: error: no template named 'optional' in namespace 'std'
    std::optional<AutoLayerForImageFilter> aboutToDraw(
    ~~~~~^
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/os.cpp:12:
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/skia_system.h:17:
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/skia_surface.h:27:
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/include/core/SkSurface.h:11:
/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/include/core/SkImage.h:198:48: error: no template named 'optional' in namespace 'std'
                                          std::optional<SkAlphaType> alphaType = std::nullopt);
                                          ~~~~~^
/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/include/core/SkImage.h:198:87: error: no member named 'nullopt' in namespace 'std'
                                          std::optional<SkAlphaType> alphaType = std::nullopt);
                                                                                 ~~~~~^
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/os.cpp:12:
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/skia_system.h:17:
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/skia_surface.h:27:
/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/include/core/SkSurface.h:41:16: warning: nested namespace definition is a C++17 extension; define each namespace separately [-Wc++17-extensions]
namespace skgpu::graphite { class Recorder; }
               ^~~~~~~~~~
                { namespace graphite        } 
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/os.cpp:12:
/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/skia_system.h:50:17: error: no member named 'Term' in 'SkGraphics'
    SkGraphics::Term();
    ~~~~~~~~~~~~^

FAILED: laf/os/CMakeFiles/laf-os.dir/skia/skia_surface.cpp.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DCMARK_STATIC_DEFINE -DGR_GL_FUNCTION_TYPE=__stdcall -DHAVE_CONFIG_H -DHAVE_CONFIG_OVERRIDE_H=1 -DLAF_FREETYPE -DLAF_MACOS -DLAF_SKIA -DLAF_WITH_REGION -DNDEBUG -DPNG_NO_MMX_CODE -DSK_ALLOW_STATIC_GLOBAL_INITIALIZERS=1 -DSK_BUILD_FOR_MAC -DSK_FORCE_DISTANCE_FIELD_TEXT=0 -DSK_GAMMA_APPLY_TO_A8 -DSK_GAMMA_SRGB -DSK_INTERNAL -DSK_SCALAR_TO_FLOAT_EXCLUDED -DSK_SUPPORT_GPU=0 -DSK_SUPPORT_OPENCL=0 -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/third_party/zlib -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/build/third_party/zlib -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/third_party/libpng -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/build/third_party/libpng -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/third_party/libwebp/src -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/third_party/tinyxml -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/third_party/pixman/pixman -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/build -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/third_party/giflib -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/third_party/jpeg -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/third_party/curl/include -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/third_party/simpleini -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/build/laf -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/src -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/third_party/stringencoders/src -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/third_party/externals/freetype/include -I/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/third_party/externals/harfbuzz/src -stdlib=libc++ -O2 -g -DNDEBUG -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -mmacosx-version-min=11.0   -Wno-c++14-extensions -Wno-ignored-attributes -Wno-unused-result -Wno-deprecated-declarations -Werror=inconsistent-missing-override -fobjc-arc -std=c++14 -MD -MT laf/os/CMakeFiles/laf-os.dir/skia/skia_surface.cpp.o -MF laf/os/CMakeFiles/laf-os.dir/skia/skia_surface.cpp.o.d -o laf/os/CMakeFiles/laf-os.dir/skia/skia_surface.cpp.o -c /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/skia_surface.cpp
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/skia_surface.cpp:12:
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/skia_surface.h:19:
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/skia_helpers.h:17:
/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/include/core/SkPaint.h:474:10: error: no template named 'optional' in namespace 'std'
    std::optional<SkBlendMode> asBlendMode() const;
    ~~~~~^
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/skia_surface.cpp:12:
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/skia_surface.h:22:
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/include/core/SkCanvas.h:26:
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/include/core/SkString.h:15:
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/include/private/SkTArray.h:15:
/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/include/private/SkTLogic.h:54:67: error: no member named 'size' in namespace 'std'
constexpr int SkCount(const Container& c) { return SkTo<int>(std::size(c)); }
                                                             ~~~~~^
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/skia_surface.cpp:12:
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/skia_surface.h:22:
/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/include/core/SkCanvas.h:69:16: warning: nested namespace definition is a C++17 extension; define each namespace separately [-Wc++17-extensions]
namespace skgpu::graphite { class Recorder; }
               ^~~~~~~~~~
                { namespace graphite        } 
/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/include/core/SkCanvas.h:2303:10: error: no template named 'optional' in namespace 'std'
    std::optional<AutoLayerForImageFilter> aboutToDraw(
    ~~~~~^
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/skia_surface.cpp:12:
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/skia_surface.h:27:
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/include/core/SkSurface.h:11:
/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/include/core/SkImage.h:198:48: error: no template named 'optional' in namespace 'std'
                                          std::optional<SkAlphaType> alphaType = std::nullopt);
                                          ~~~~~^
/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/include/core/SkImage.h:198:87: error: no member named 'nullopt' in namespace 'std'
                                          std::optional<SkAlphaType> alphaType = std::nullopt);
                                                                                 ~~~~~^
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/skia_surface.cpp:12:
In file included from /Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/aseprite/laf/os/skia/skia_surface.h:27:
/Users/jsomedon/Developer/build_aseprite_on_mac.sh/buildroot/skia/include/core/SkSurface.h:41:16: warning: nested namespace definition is a C++17 extension; define each namespace separately [-Wc++17-extensions]
namespace skgpu::graphite { class Recorder; }
               ^~~~~~~~~~
                { namespace graphite        } 


```
### Aseprite and System version

* Aseprite version: v1.3-beta14
* System: macOS 12.3.1 on m1 Pro

**Comment by dacap** [comment] 2022-05-11 12:17
Hi @jsomedon, we have updated some requirements to compile Aseprite (and Skia): you need a compiler with C++17 support, is it probable that you are using an older Xcode version?

**Comment by jsomedon** [comment] 2022-05-11 13:53
My Xcode is 13.3.1. My developer's tool is also 13.3.1.

**Comment by dacap** [comment] 2022-05-11 14:34
Oh from the log, it looks like the problem is not Skia, but your local copy of Aseprite. Are you compiling the main/beta branch? or a release? You should use the latest main/beta commit if you are going to use m102 (because it includes the required C++17 flags).

**Comment by dacap** [comment] 2022-05-11 14:35
Closing this issue because the issue is the incompatibility of trying to compile the latest release with the new skia when C++17 flags are required (which it's already fixed in main/beta branches).

**Closed** 2022-05-11 14:35 UTC
Labels: macos, compilation
