### ISSUE TITLE
Crash when opening existing sprite with latest beta

### ISSUE THREAD

**Issue by jameswilddev** [aseprite/aseprite#1531] opened 2017-07-09 10:04 UTC
I have an Aseprite file from a few versions ago which I can open in the current stable version, but not the latest beta; Aseprite hangs then crashes to desktop.

This may be related to a large number of overlapping tags in the file, but I'm not sure
[character.sprit-e.zip](https://github.com/aseprite/aseprite/files/1133652/character.sprit-e.zip)

.

### Aseprite and System version

* Aseprite version: from Steam, v1.2-beta12 to reproduce, v1.1.13 to open successfully.
* System: Dell XPS 13 FHD, Windows 10 Home Creators' Update

**Comment by JosefKuchar** [comment] 2017-08-19 16:41
I have lastest dev version from master branch compiled like 3 days ago and it works for me.
System: Windows 10 Pro

**Comment by dacap** [comment] 2017-08-19 18:03
I've tested this in v1.2-beta12 macOS and it works. Anyway I'll try to give a try into Windows 10 but next week.

**Comment by dacap** [comment] 2021-08-18 18:02
I'm closing this issue because I wasn't able to reproduce it anymore in v1.2.28.

**Closed by dacap** 2021-08-18 18:02 UTC
Labels: bug, high priority
