### ISSUE TITLE
1D Grid Index in status bar

### ISSUE THREAD

**Issue by Paperdomo101** [aseprite/aseprite#4585] opened 2024-08-03 11:28 UTC
I think it would be convenient if the grid coordinate was also displayed in 1D, eg. 4x4 grid: (3, 2) = 11.
![2d index](https://github.com/user-attachments/assets/9a1f9d7d-121a-4117-b26e-d5f4ccbea206)

* Aseprite version: 1.3.7
* System: all

**Comment by dacap** [comment] 2024-08-12 13:41
Closing this as I think it's duplicate of #2082

**Closed by dacap** 2024-08-12 13:41 UTC
Labels: feature, ui
