### ISSUE TITLE
Inconsistent mouse wheel action.

### ISSUE THREAD

**Issue by buckle2000** [aseprite/aseprite#2364] opened 2020-05-04 04:34 UTC
Mouse wheel up = Zoom in (make image bigger)
Ctrl + Mouse wheel up = Decrease brush size (make brush smaller)

In my mind, they are rather opposite. I'm used this software for half a year now, and I still can't remember the correct direction to scroll.

Please add an option to invert either option. Perhaps you should make *Ctrl + Mouse wheel up = In crease brush size* by default?

### Aseprite version

* Aseprite version: 1.2.18-dev

**Comment by rikman81** [comment] 2020-05-25 06:49
New Aseprite user here and this is the first thing I noticed as it feels so unintuitive to scroll up for smaller and down for bigger.

Looked through the options to see if there was a toggle, then ended up here after some Google-Fu, so a big +1 for the toggle option of changing scroll wheel direction.

**Comment by dacap** [comment] 2020-05-25 15:56
I'll try to review the mouse wheel behavior on all platforms comparing them with similar programs (probably I'll make a document about it with some information about how mouse wheel work on different programs/platforms and post a link here).

**Comment by OsthatoAlfakyn** [comment] 2020-08-28 22:52
I thought it was worth pointing out that when hovering over the brush size and scrolling, mouse wheel up _increases_ the size (which makes sense to me), while using the brush tool on the canvas and hitting ctrl + mouse wheel up _decreases_ the size. I don't really mind either way, but the inconsistency is really throwing me for a loop

**Comment by wdtfshi** [comment] 2021-01-07 18:52
Any update on this "issue"? It took me quite a while to find this thread in hope of a solution but looks like it's still the case. I've even tried to make scrips with a third party program to invert this mouse wheel function but with no luck. It would be really nice to see an option to invert it on the preferences settings for Aseprite.

**Comment by TehThanos** [comment] 2021-05-04 22:44
Just discovered this is a duplicate of #1801 which already has [this](https://github.com/aseprite/aseprite/pull/2403) pull request to close it.

**Comment by dacap** [comment] 2021-05-04 23:36
It looks like the only customization required is changing the up/down mouse wheel direction for increasing/decreasing the brush size, *AND*, only on Windows (because on macOS it works correctly). I'll review both pull requests later (#2403 and #2715) and create another issue with a summary of the mouse wheel functionality, at the moment I think that #2715 makes more sense because it's easier to merge, but I have to check the cross-platform issues and set the new default value for Windows (and Linux probably). As I said it looks like macOS is working as expected.

**Closed** 2022-05-05 13:00 UTC
Labels: bug, ui
