### ISSUE TITLE
Setting to treat a group layer as if it were a merged layer

### ISSUE THREAD

**Issue by coyo-t** [aseprite/aseprite#3249] opened 2022-04-13 05:31 UTC
This is something [Krita does](https://docs.krita.org/en/user_manual/layers_and_masks.html#how-are-layers-composited-in-krita) that is exceptionally helpful and I feel it would greatly increase Aseprite's flexibility, especially in what you can do with scripting.

For example, using `layer:cel()` on a group layer currently just returns `nil` regardless of if the combined output would have a cel there or not, but with it being treated as a combined layer, it would return a cel. This would make what I'm currently trying to do in a script much simpler, as I wouldn't have to kind-of jankily duplicate+merge a group, then remember to remove it from the sprite later on, just to get a cel/image data from it.

As well as that, "non-passthrough" ("Sandboxed"? "Isolated"? "Deferred"?) layer groups can have their opacity and blend modes set, since to the layer stack they're pretty much no different than a regular layer.

A non-scripting example would be easy masking (assuming Aseprite gets an erase blend mode, or other alpha-dependent BMs), as the mask layer would only affect layers below it that are *also* in the group. In fact, the "mask layer" *itself* could be a sandboxed group with the erase blend mode.

I'm not sure where the "Compositing(?) option" for layer groups would live, probably only in the layer properties dialog (as the toggles on the left of the layers panel is already pushing it for button count)

**Comment by dacap** [comment] 2022-04-22 13:07
Hi @coyo-t, this is a duplicate of #3225, anyway I'm not sure if the Lua API will offer a direct access to the "composited cel" of the group (not yet sure how this will be finally implemented yet).

**Closed by dacap** 2022-04-22 13:07 UTC
