### ISSUE TITLE
Layer Mask

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#3761] opened 2023-03-17 21:00 UTC
Just a feature request for an opacity mask layer function like the kind you see in CSP or SAI.
Essentially an 8bit greyscale Cel that can be applied to the Cel (or Cels) a layer above that reveals only corresponding pixels with a nonzero value; v=255 completely reveals the pixels in the attached Layer(s), value zero completely hides them.

Ideally, the mask could be applied to single Layers, Layer Groups, or all Layers below. The mask should be editable on a per-Cel (per-Frame) basis, too.

This is probably a duplicate but I could not find anything that mentioned it specifically.
I also understand that there is a way to do this with the Lock Alpha ink mode, but I cannot figure out how it works exactly.

Anyway thank you for considering it! :D

..using ASEprite b.1.3-21-x64 on Win10.

**Comment by dacap** [comment] 2023-03-18 00:29
Hi @oceanhahn, I think duplicate of #459, we hope to have some kind of mask layer implemented when the new shader-based rendering engine is done #3516

**Closed by dacap** 2023-03-18 00:29 UTC

**Comment by oceanhahn** [comment] 2023-03-18 05:00
Oh, I see. Thanks, sorry for making you do that bit of deskwork unnecessarily!
The links to the other issues was handy though! Thanks again!

(Just so that I am not totally confused, this was closed as a duplicate, not because it is already in there, right? ^^;)
