### ISSUE TITLE
Very bad cursor lag on Linux

### ISSUE THREAD

**Issue by arcooke** [aseprite/aseprite#957] opened 2016-02-08 22:55 UTC
Hey-  Sorry if this is a duplicate post.  I searched around and saw a couple mentions about cursor problems, but one was for Mac, and the other was unrelated.

I just purchased Aesprite from the website a little while ago and this issue is really bad on Linux.  I tried out the experimental system cursor option, but the lag persists and double cursors get drawn as mentioned in #913.

Here is a video demonstrating how bad the lag is: https://www.youtube.com/watch?v=6DNTQ_A37b4

I am on Mint 17.3 KDE (Ubuntu 14.04 base)

Is a fix planned for this soon?  It actually works perfectly fine through Wine, so that's what I'll have to do for now.

**Comment by edwinhollen** [comment] 2016-02-12 20:12
I would like to confirm this issue on Ubuntu 14.04 LTS with Aseprite v1.1.1. I was going to post a video, but @arcooke's demonstration is the exact issue I'm experiencing. 

I also want to add that enabling/disabling the native cursor option seems to have no effect on this issue.

**Comment by dacap** [comment] 2016-02-12 21:25
Hi there! This issue might be solved when #139 is finished. Not for v1.1.2, but maybe in a v1.1.3 or v1.2 (the v1.1 branch got a lot of new issues anyway, I think I'll jump to v1.2 soon anyway.)

This is in someway strange because I cannot reproduce the lag. Anyway I'm using Ubuntu 14.04 on virtual machine (I don't know if that should be better or worse).

**Comment by arcooke** [comment] 2016-02-12 21:56
@dacap Thanks for responding.  

Hardware can behave weirdly in a virtual machine. There's a lot of hardware ownership swapping going on to decide which OS can take control of devices. In some cases, virtual device drivers on the guest OS that are piggy backing off the host system's drivers.  I wouldn't be surprised at all if you aren't seeing this behavior on a virtual machine.  Running the VM in full screen mode might invoke full ownership transfer to the guest OS, which could help you replicate the problem.

There is some info here about how this all works: https://www.virtualbox.org/manual/ch01.html#keyb_mouse_normal

I saw you mention in #599 that you don't have access to a linux machine to test on.  You don't need one.. it's really easy to get linux up and running on your existing hardware without making any system changes if you have a couple of USB sticks laying around.

* Download an Ubuntu ISO.  Get the installer on a USB stick with [Unetbootin](http://unetbootin.github.io/)
* Reboot with both your installer USB and a blank USB stick plugged in, make sure your bios is configured to boot from USB first.
* Run through the Ubuntu installer, and install directly to the blank USB stick.
* I'd recommend installing proprietary graphics card drivers after you get into Ubuntu, to make sure you're running in a typical user scenario.

Now, any time you want to test a linux release, all you have to do is reboot the computer with the Ubuntu stick plugged in.. and it will use all of your hardware natively.

**Comment by LiquidityC** [comment] 2016-02-23 22:06
The referencing commit above does solve this issue on my archlinux/X11 setup. Most likely it will solve the cases on other distros as well

**Comment by dacap** [comment] 2016-02-24 12:09
Thanks for the info @LiquidityC 

I'll close this issue but it might be re-opened in the future if someone else confirm that the bug still persists.

**Comment by sirblackheart** [comment] 2016-02-26 13:57
I can confirm that this greatly improves mouse performance on archlinux/wayland(1.10)/libinput(1.2). It still is not as smooth as the cursor acts outside the aseprite window but makes aseprite finally usable on linux for me.

**Comment by Brottweiler** [comment] 2016-02-29 16:40
This latest update (`1.1.2`) fixed the mouse lag, as @sirblackheart describes there's still a very slight delay, but atleast I can use the program now... actually I can't press anything, well that's another bug.

**Closed** 2016-03-01 01:25 UTC
Labels: bug, high priority, linux

**Comment by GizmoCodes** [comment] 2016-03-20 21:16
Oh, that fixed? That's a lie. I'm on Aseprite 1.1.3-dev (And even though I know its not really supported), the problem is there. On a Fedora 23 remix.

**Comment by arcooke** [comment] 2016-03-20 21:19
@GizmoCodes The original issue I reported in this thread is indeed fixed, nobody is lying.  I'm running 1.1.3 and it's running perfectly fine.  If it is still happening in Fedora you should submit a new issue

**Comment by dacap** [comment] 2016-03-20 21:30
Hi @GizmoCodes, could you please create another issue specific to Fedora with a video about how slow it is running? Also it would be great to know if you've compiled Aseprite with debug flags or release flags, and what specific commit you are using

**Comment by dacap** [comment] 2016-03-20 21:32
P.S. I forgot, please @GizmoCodes read our [code of conduct](https://github.com/aseprite/aseprite/blob/master/CODE_OF_CONDUCT.md)

**Comment by allrod5** [comment] 2016-12-27 18:22
I'm not sure if I should open a new issue, but I am using Aseprite v1.1.11 from Steam in Ubuntu 16.04 and the cursor lags (something about 250~500ms movement delay). It is usable, but really annoying.

I may have some time in the upcomming weeks to try out building v1.2-beta5 to see if anything changes.

An observation, I don't know if is useful: if I move the cursor fast to the outside of the Aseprite window, when I reach the actual 'outside' the system shows the cursor system-rendered now, as expected, but the lagged cursor in Aseprite will stop in the delayed position and will stay there until the cursor reaches the Aseprite window again.
