### ISSUE TITLE
Text Spacing error in 'Help' -> 'Documentation'

### ISSUE THREAD

**Issue by EklofLogan** [aseprite/aseprite#3553] opened 2022-10-11 23:23 UTC
May not be a bug, could be intentional, but when you click 'Help' -> 'Documentation', it opens a README window. In this README, it is just the same text as this repositories README, only the spacing after links is gone. So in the second bullet point for example, it say's "... of layers & framesas separated ..." but it should say "... of layers & frames as separated ...". It does this for all links in the README.

### Aseprite and System version

* Aseprite version: v1.2.30-x64, installer
* System: Windows 10

**Comment by dacap** [comment] 2022-10-11 23:31
Hi @EklofLogan, thanks for this report, actually this is duplicate of #3543, more details about all the issues in the README view were reported here: https://community.aseprite.org/t/readme-whitespace-issues/15881

**Closed by dacap** 2022-10-11 23:31 UTC
Labels: bug, duplicate
