### ISSUE TITLE
Incorrect Behavior Of Links In "About"

### ISSUE THREAD

**Issue by ElderlyGlek** [aseprite/aseprite#3719] opened 2023-03-02 23:40 UTC
Incorrect behavior of links in "About", for clarity, I highlighted some problems in the screenshot (alignment, spaces, commas, etc.):

![About](https://user-images.githubusercontent.com/69088106/222582675-5249e35e-a78f-4f1c-ae19-cdfac999dfa8.png)

Also, at 100% screen scaling and 200% UI scaling, the text gets slightly taller.

### Aseprite and System version

* Aseprite version: v1.3-rc1-dev
* System: Windows, 10 Pro 21H2, OS Build: 19044.1766

**Comment by dacap** [comment] 2023-03-03 18:05
Duplicate of #3543 / https://community.aseprite.org/t/readme-whitespace-issues/15881

**Closed by dacap** 2023-03-03 18:05 UTC
Labels: bug, duplicate, low priority, time-3
