### ISSUE TITLE
"Experimental > Use native mouse cursor" breaks scrollbars

### ISSUE THREAD

**Issue by ssokolow** [aseprite/aseprite#599] opened 2015-02-21 06:20 UTC
In Aseprite v1.0.9-dev (as compiled from the release-tag tarball for 9546c0a5e3bcbc8e707a08ed83d9545a30c3c568 on Lubuntu Linux 14.04 64-bit just now), enabling "Experimental > Use native mouse cursor" makes it impossible to drag scrollbars.

Specifically, they shudder back and forth with an overall motion of zero in response to a smooth, continuous drag in one direction.

**Comment by dacap** [comment] 2015-02-21 18:02
Hi there! I think that "Native mouse cursor" feature should be disabled/hidden on Linux, it was created for Windows and Mac OS X. Mainly because I don't have a real PC with Linux installed on it, so I cannot test how the native cursor works (VMs are tricky to reproduce mouse UI issues).

**Comment by ssokolow** [comment] 2015-02-22 01:39
Leave it. Until Aseprite fixes #283 (events backlog and cause the GUI to lag)" issue, anything which can shave away at the amount of work to be done to handle a mouse event is welcome. It's filed under experimental and that should be enough.

(Plus, it IS usable if you know to either click outside the handle to scroll or repeatedly grab and release the scrollbar in tiny increments so the pointer warping isn't triggered.)

**Comment by GeertJohan** [comment] 2016-01-23 21:00
I think this issue can be closed. For me this is not a problem anymore.
v1.1.1 release binary, ubuntu 15.10

I do prefer keeping the "Native mouse cursor" feature as long as #913 is not released.

**Comment by dacap** [comment] 2016-02-12 22:03
I'll close this issue. Thanks @GeertJohan.

**Closed by dacap** 2016-02-12 22:03 UTC
Labels: linux
