### ISSUE TITLE
Pasting an image from Firefox changes the colors unexpectedly

### ISSUE THREAD

**Issue by KashouC** [aseprite/aseprite#2488] opened 2020-08-13 23:03 UTC
I saw there was a commit about this here: https://github.com/aseprite/aseprite/commit/f3e9978bb002673c2fa75c6ec7c70e270a4d969f

Probably related, or if this is the bug you already found for 1.2.25, but if you copy an image over from Firefox the colors will get changed around. Works fine from Vivaldi or Discord.

Link to image: https://i.imgur.com/28Y0HlS.png

![firefox image copy color bug](https://user-images.githubusercontent.com/17066488/90195330-6f147c80-ddc9-11ea-9593-e4b6bcf45650.gif)

Aseprite 1.2.24-x64
Windows 10

**Comment by mig-moog** [comment] 2020-08-14 02:33
I have also encountered this issue!  

this is the palette as intended: 
![image](https://user-images.githubusercontent.com/57271984/90207648-cfe58a00-ddb4-11ea-9367-c081dccad54d.png)

and this is the palette when pasted from firefox:
![Sprite-0005](https://user-images.githubusercontent.com/57271984/90207697-ef7cb280-ddb4-11ea-8f8c-e57cdb569c92.png)

**Comment by dacap** [comment] 2020-08-14 13:52
That's right @KashouC! That commit is a fix for this issue, I'm fixing a couple of extra things and will release v1.2.25 this Monday. Please contact me at support@aseprite.org in case that you need the fixed .exe ASAP

**Comment by KashouC** [comment] 2020-08-14 14:10
Nah I use Vivaldi ^^ Just made a report for someone else in case it wasn't this bug.

**Closed** 2020-08-18 14:14 UTC
