### ISSUE TITLE
Custom Brush Paintbrush Mode Is Broken

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#1261] opened 2016-09-21 00:21 UTC
It's possible I'm missing something, but paintbrush mode for brushes seems broken. 
Here's Aseprite 1.1.5:
![hi 1 1 5](https://cloud.githubusercontent.com/assets/8582123/18693507/243f08f8-7f70-11e6-8193-bc0a189d4a48.gif)
(I didn't check the very latest version it worked as expected. I probably would have if I hadn't accidentally submitted this issue before I finished writing it :P  )
Here's Aseprite v1.2-beta2:
![hi 1 2-beta2](https://cloud.githubusercontent.com/assets/8582123/18693605/09b83dfa-7f71-11e6-81eb-76c154569823.gif)

Essentially the brush is stamped once, and never again.
### Aseprite and System version
- Aseprite v1.2-beta2 Steam
  Windows Vista 32 Bit

**Comment by dacap** [comment] 2016-09-21 17:07
Hi @KasumiArai! This regression was introduced in 18b4008c6f76cc57fc166be01e201ebc0d0d7377 to fix [this bug](https://twitter.com/Legacydev_/status/777848152384802817)

The issue here is that the transparent color is being draw/copied as part of the brush (because the brush is created with a box):

![brush-bug](https://cloud.githubusercontent.com/assets/39654/18720883/3d1b44f6-8004-11e6-9858-899617d45641.gif)

You could try to create the brush with the exact shape from the selection (e.g. using the Magic Wand tool and then Ctrl+B) and it should work as expected:

![brush-fine](https://cloud.githubusercontent.com/assets/39654/18720908/4bfd7642-8004-11e6-869a-f5d9438d18f7.gif)

I think this issue should be finally fixed implementing #945, so with "Simple Ink" the transparent color should act like the old behavior (compositing alpha), and with the "Copy Alpha-Color" ink it should act with the new behavior (replacing alpha).

**Comment by KasumiArai** [comment] 2016-09-22 00:38
I understand the simple ink, but I also get this behavior with Alpha Compositing which I believe does not make alpha 0 behave as the eraser. #945 may cover that, but I'm mentioning this just in case.

**Comment by dacap** [comment] 2016-09-22 13:30
> I understand the simple ink, but I also get this behavior with Alpha Compositing which I believe does not make alpha 0 behave as the eraser. #945 may cover that, but I'm mentioning this just in case.

Actually the ink mode is almost completely ignored with a custom brush (#945 should fix this). The "Simple Ink" should work as you expected (old behavior en v1.1.5), and the "Copy Alpha+Color" should work as it's working now in v1.1.8.

> there's three alphas, though. The Opacity Value, the Alpha Value of the brush's pixels, and the Alpha value of the foreground color.

Indeed there are four alphas: the opacity value, alpha in brush pixels, alpha en foreground, and the new "mask bitmap" (which is the original selection used to create the brush).

> I suppose the thing is that brush never blends with itself, so why the magic wand tool thing works is that it takes those pixels out of the equation. A transparent pixel meanwhile is still "drawn" so it will overwrite the current stroke because the current stroke cannot blend with the current stroke. Is this correct?

Yes, it's correct.

>  I guess ideally I'd like transparent pixels to be treated as not there in Alpha Compositing like pixels that were eliminated from the selection that created the brush. Simple ink could still "bring them back" so to speak.

Actually Simple Ink acts like Alpha Compositing with Opacity=foreground color alpha. So Simple ink and Alpha compositing with custom brushes should act like in v1.1.5. And "Copy Alpha+Color" is the only one that should copy the alpha value directly.

**Comment by dacap** [comment] 2016-09-22 13:30
I forgot, there is some documentation in the website about ink modes: http://www.aseprite.org/docs/ink/

**Comment by KasumiArai** [comment] 2016-09-22 14:02
I had read that page, which is where I got Simple Ink "bringing back pixels" to use as the eraser. 

Basically when I read, what I got from it was that a fully transparent pixel (that was still part of the selection) would act as the eraser. What I think I've learned from this discussion is that pixels of the brush (whether they have alpha values, or whether they are part of the mask bitmap, or anything else that can be different) would not make a difference between simple ink and alpha compositing. 

The difference between the two is solely that when the alpha value of the selected color itself i.e. here: 
![alphaforeground](https://cloud.githubusercontent.com/assets/8582123/18751039/8165f780-80ab-11e6-8ab3-dc9277fb55a0.png)
is zero, simple ink will erase, and alpha compositing won't. I even realize that the documentation does specifically state foreground color, so I'm not even sure how to change it in a concise way where I'd have understood correctly. But I get it now. (Unless the above explanation is wrong >_>)

**Comment by dacap** [comment] 2016-09-22 14:07
I'll see how to improve the docs, maybe one gif for each case.

**Comment by dacap** [comment] 2016-09-23 16:19
I was trying to fix this for the next release, but the painting is not working correctly for brushes with alpha != 255 (this is from v1.1.7):

![bug](https://cloud.githubusercontent.com/assets/39654/18793190/00574096-8190-11e6-99a7-ca9f0e6b38d7.gif)

Leaving this for other release.

**Comment by oceanhahn** [comment] 2016-10-18 01:48
I accidentally reposted this issue, but I'm wondering if anyone in this discussion has mentioned how transparent custom brush pixels seem to behave differently in indexed mode compared with RGB mode?

![stamp alpha overwrite 2](https://cloud.githubusercontent.com/assets/11544843/19461538/57543c24-94b3-11e6-9efb-ccdf4552cca5.gif)

**Comment by MetinSeven** [comment] 2017-02-21 14:55
The missing transparency issue in a grabbed paint brush is still apparent in 1.1.13 for MacOS. Will it be fixed in the next MacOS update? That'd be great, thanks in advance.

**Comment by dacap** [comment] 2019-09-24 12:08
This issue should be fixed in recent versions.

**Closed by dacap** 2019-09-24 12:08 UTC
Labels: bug, high priority, sprite editor
