### ISSUE TITLE
Cannot paste printscreened things into Aseprite (Regression?)

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#1122] opened 2016-05-07 04:19 UTC
This is an unusual one. When I paste an image copied to the buffer with the print screen key, I just get a fully transparent screen, but the dimensions are correct. 

Here is a gif
![printscreenfail](https://cloud.githubusercontent.com/assets/8582123/15090080/5595cfa4-13e6-11e6-8c53-6f23d91cd212.gif)
I draw a smiley face, then copy it. Create a new document (you can see that the new document's size is 32x32, the size of the face.) I paste the face. Then I press printscreen. I create another new document. (You can see the dimensions are now 1920x1080, my monitor's size.) I press printscreen on the new document dialog as well. I paste. It's just blank. Then I click Aseprite v.0.9.5, create a new document and paste it there successfully. 

The last version I can paste a printscreen in (that I have) is 1.1.4.1. I have a gif of me trying the same paste in 1.1.4.1, 1.1.5, 1.1.5.1, and 1.1.5.2 I can send if needed, but it ended up being nearly 4MB. Regardless, only 1.1.4.1 works.

Just for clarity reproduction steps for me are simply:

1. Press print screen (or alt+print screen)
2. Paste.

A selection will be created of the right size, but with fully transparent pixels.
Aseprite 1.1.5.X on Windows Vista 32bit.

**Comment by dacap** [comment] 2016-05-07 22:47
Hi @KasumiArai, this bug is already fixed in my local copy (originally reported here: https://twitter.com/Legacydev_/status/728537736550944772) It's a regression introduced when we switched the clipboard management to the [clip](github.com/aseprite/clip) library to support OS X copy/paste.

The problem only appears when Windows is running on 32bpp. It's because Windows doesn't include alpha/transparent information in the image. If you paste the image on MSPaint, copy it again, the image is converted to 24bpp an then you will be able to paste the screenshot on Aseprite.

Reference commit 160418daeade414c89509ac9c3845d9df4708261

**Comment by KasumiArai** [comment] 2016-05-08 07:36
Good to hear! I was worried it was some weird thing with my PC setup.

**Closed** 2016-05-10 14:15 UTC
Labels: bug, critical
