### ISSUE TITLE
[Regression] Shift+Ctrl line functionality draws an additional line

### ISSUE THREAD

**Issue by nettleflap** [aseprite/aseprite#3243] opened 2022-04-09 11:09 UTC
When I hold Shift+Ctrl to draw a straight line that snaps to a 22.5 increment angle and click to draw the line, it draws an additional second line from the visible endpoint to where the cursor is.

![linebugase](https://user-images.githubusercontent.com/8578188/162569280-4d3bd8ad-a1bc-44e8-a615-8e9d1ebb4914.gif)

I experienced this for the first time around Feb 11.

This is a regression, it wouldn't draw the additional line before. It wastes quite a lot of time in total for daily use since every time I have to erase the additional line.

### Aseprite and System version

* Aseprite version: 1.2.34.1-x64, Steam.
* System: Windows 10.

**Comment by lunathir** [comment] 2022-04-09 13:02
Duplicate of #3196

**Comment by dacap** [comment] 2022-04-11 12:13
Thanks @nettleflap and @lunathir for the bug reports, it looks like a duplicate, anyway the gif image to see the bug is really helpful.

**Closed by dacap** 2022-04-11 12:13 UTC
Labels: duplicate
