### ISSUE TITLE
"--sheet --list-layers --split-layers" exponentially clone layers in JSON

### ISSUE THREAD

**Issue by m4c0** [aseprite/aseprite#1234] opened 2016-08-15 17:28 UTC
Using a version build from GIT and the attached ASE (a simple file with one frame and two layers), I found a bug while generating a sheet with this command:

`aseprite -b --list-tags --format json-array --sheet chunks.bmp --data chunks.json --list-layers --split-layers chunks.ase`

The generated JSON file got four layers inside "meta", instead of two. If I add a third layer, I get a file with nine entries.
### Aseprite and System version
- Aseprite (version number, installer/portable/Steam/beta/dev):
  Build from GIT - e20fdc0812da814c9a5a481231bd3c4be74fb9be
- System (Win/OSX/Linux, version, distribution):
  OSX 10.10.5
### Attachments
- [Archive.zip](https://github.com/aseprite/aseprite/files/418548/Archive.zip):
  Contains original ASE file and generated BMP+JSON files

**Comment by mrspeaker** [comment] 2019-08-03 19:35
Is this still an issue? I tried to reproduce it by running the example command on `chunks.ase` using `Aseprite 1.3-dev`, on OSX 10.14.5. The `meta.layers` array in chunks.json correctly has two values, not four.

**Comment by dacap** [comment] 2019-10-24 22:28
I tried to reproduce it and wasn't able. I'll close this issue because it looks fixed (or at least it's already fixed in the `master` branch)

**Closed by dacap** 2019-10-24 22:28 UTC
Labels: bug
