### ISSUE TITLE
Aseprite CLI not exporting layer in --file-format

### ISSUE THREAD

**Issue by jestarray** [aseprite/aseprite#3101] opened 2021-12-16 21:27 UTC
```
aseprite <test>.ase --data <test>.json --format json-array --sheet <test>.png --split-layers --ignore-empty --shape-padding 1 --trim --filename-format "{layer}-{frame}" --batch
```

Replace <test> with the name of your ase file and the generated json does not contain the layer name:
```json
   {
    "filename": "-11",
    "frame": { "x": 269, "y": 0, "w": 24, "h": 30 },
    "rotated": false,
    "trimmed": true,
    "spriteSourceSize": { "x": 3, "y": 2, "w": 24, "h": 30 },
    "sourceSize": { "w": 32, "h": 32 },
    "duration": 120
   },
   {
    "filename": "-12",
    "frame": { "x": 294, "y": 0, "w": 24, "h": 30 },
    "rotated": false,
    "trimmed": true,
    "spriteSourceSize": { "x": 3, "y": 2, "w": 24, "h": 30 },
    "sourceSize": { "w": 32, "h": 32 },
    "duration": 120
   },
```

Interestingly this does work in the UI, just not the CLI. Someone tested this using the latest Aseprite 1.3 beta 7.

**Comment by jestarray** [comment] 2021-12-17 05:43
Just confirmed it for myself, 1.3 beta 7 on Windows 10

**Comment by PacaPop** [comment] 2021-12-21 11:24
Same issue here! The {layer} tag is not exported when you select "Visible layers" or "Selected layers" in the "Layers" selector. If you select a specific layer, the layer tag works OK. But you lose the functionality to export multiple layers in the same spritesheet
![Captura de pantalla de 2021-12-21 08-22-48](https://user-images.githubusercontent.com/95740543/146922298-9be334b9-1261-4ac4-b565-a3d887810652.png)
.

**Comment by iamOgunyinka** [comment] 2022-01-21 11:58
After some checks here and there, I realize Aseprite's CLI parser is actually sensitive to arguments' position (in this context). If you move the filename `<test>.ase` file to the end of the argument list, you'll see your command work. 

`aseprite --data <test>.json --format json-array --sheet <test>.png --split-layers --ignore-empty --shape-padding 1 --trim --filename-format "{layer}-{frame}" --batch <test>.ase`

**Comment by iamOgunyinka** [comment] 2022-01-25 09:45
@PacaPop I'm trying to reproduce the bug you reported [here](https://github.com/aseprite/aseprite/issues/3101#issuecomment-998700082) but I'm having issues understanding the behavior you expected in this regard. In a sprite with **multiple** visible layer, if you specify the `{layer}` tag, could you please describe what you expect to see as the layer name(s)?

**Comment by iamOgunyinka** [comment] 2022-01-25 10:06
@PacaPop I'm trying to reproduce the bug you mentioned in the screenshot attached. Please, could you describe the behavior you expect to see in (the resulting JSON data of) a sprite with **multiple** visible layers where these layers are not specified to split? I've been testing this part for some hours now and all my tests come out fine, so please walk me through it. Thanks.

**Comment by martincapello** [comment] 2022-01-25 13:35
Hi @jestarray 👋, according to Aseprite CLI's help:
```
Usage:
  aseprite [OPTIONS] [FILES]...
``` 
So, the files go at the end of the command line arguments, hence it is not a bug actually. Although, we could improve this by warning the user about such argument ordering issue 🤔

**Comment by jestarray** [comment] 2022-01-25 18:22
@martincapello Ohh I see! welp, you can close this issue now unless you want to keep it open until notifying the user is implemented

**Comment by dacap** [comment] 2022-02-02 12:20
Actually I think the only problem is putting the <test>.ase file before --split-layers instead of doing after it, something like this should work:

    aseprite --split-layers test.aseprite --data test.json --format json-array --sheet test.png --ignore-empty --shape-padding 1 --trim --filename-format "{layer}-{frame}" --batch

It's mentioned in the [--split-layers docs](https://www.aseprite.org/docs/cli/#split-layers):

> Splits the visible layers of **the next document** in the command line, so then you can save each layer as an independent image/item. It affects --sheet and --save-as options. Warning: The --split-layers option must be **before your sprite**.

It's an odd behavior but it is as it is right now, we would like to replace the whole CLI with export pipelines/scripts/actions/macros in a far future. This could be fixed in several ways:
1) if there is just one input .ase, just split the layers of that file in the sprite sheet (whatever --split-layers is located),
2) if there are multiple files in the .ase we might want to keep the behavior (so some files might be --split-layers and other no, in case that we're creating a texture atlas)
3) automatically split layers in sprite sheet if filename-format includes {layer}

**Comment by martincapello** [comment] 2022-05-12 20:14
Closing this because it is not a bug actually. @PacaPop described a different issue, so if you are still having problems with this, could you please create a new issue describing it in more detail? We were trying to reproduce it without success, thank you.

**Closed by martincapello** 2022-05-12 20:14 UTC
Labels: bug, medium priority, cli, time-3
