### ISSUE TITLE
Curl compilation failed on Ubuntu 16.04

### ISSUE THREAD

**Issue by Wargog** [aseprite/aseprite#1058] opened 2016-04-12 22:18 UTC
When running make on XUbuntu 16.04 with the release zip for version 1.1.4 curl fails to link statically into the aseprite binary and throws the following error:
```
[100%] Built target app-lib
Scanning dependencies of target aseprite
[100%] Linking CXX executable ../bin/aseprite
../lib/libcurl.a(ssluse.c.o): In function `ossl_connect_step1':
/home/joshua/Workspaces/aseprite/third_party/curl/lib/ssluse.c:1473: undefined reference to `SSLv3_client_method'
collect2: error: ld returned 1 exit status
src/CMakeFiles/aseprite.dir/build.make:165: recipe for target 'bin/aseprite' failed
make[2]: *** [bin/aseprite] Error 1
CMakeFiles/Makefile2:171: recipe for target 'src/CMakeFiles/aseprite.dir/all' failed
make[1]: *** [src/CMakeFiles/aseprite.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by sirblackheart** [comment] 2016-04-13 15:27
duplicate of #1043 ?

**Comment by Wargog** [comment] 2016-04-13 17:04
Possibly, but I read that issue before posting and that is not my error, doing everything OP in that issue said to fix didn't work, and I ended up getting the same error each try

**Comment by sirblackheart** [comment] 2016-04-13 20:39
```
../lib/libcurl.a(ssluse.c.o): In function `ossl_connect_step1':
/home/joshua/Workspaces/aseprite/third_party/curl/lib/ssluse.c:1473: undefined reference to `SSLv3_client_method'
```

it is the same error. compiling with -DUSE_SHARED_CURL=ON meaning dynamic linked curl works for now.

**Closed** 2016-08-30 02:43 UTC
Labels: compilation, linux
