### ISSUE TITLE
Please add a switch which can disable one/some frame(s) in a tag sequence temporarily

### ISSUE THREAD

**Issue by Rogemcy** [aseprite/aseprite#4557] opened 2024-07-04 01:17 UTC
Please add a switch which can disable one/some frame(s) in a tag sequence temporarily by right click the frrame(s) , for preview the tag animation loop playing without this/these frame(s) .Thanks!(I'm not good at english speaking , sorry for that ) 

### Aseprite and System version
* Aseprite version:1.3.7  Steam 
* System: Windows10

**Comment by dacap** [comment] 2024-07-04 13:47
Hi @Rogemcy, this is duplicate of #244.

There are some progress in #4409 to start experimenting manipulating the visibility of some frames/tags. But not yet fully tested/done.

**Closed** 2024-07-04 13:47 UTC
Labels: duplicate
