### ISSUE TITLE
Aseprite Thumbnailer Doesn't Work With The Portable Version

### ISSUE THREAD

**Issue by ElderlyGlek** [aseprite/aseprite#4840] opened 2024-11-30 01:42 UTC
The [aseprite-thumbnailer](https://www.aseprite.org/thumbnails/) doesn't work with the portable version, what can I do to make the thumbnails display correctly with the portable version? I don't want to use the installer, as I prefer portable versions of programs.

**Comment by dacap** [comment] 2024-12-02 11:19
Hi @ElderlyGlek, actually the aseprite-thumbnailer is intendent from the portable version. You can install the thumbnailer without installing/or having any Aseprite .exe at all, as the thumbnailer .dll already have the decoder/rendering code inside it.

So I'm not sure how is it that it's not working, did you install it? (there is a .bat file to associate the .dll with the .ase/.aseprite file format).

**Comment by ElderlyGlek** [comment] 2024-12-02 16:22
> So I'm not sure how is it that it's not working, did you install it? (there is a .bat file to associate the .dll with the .ase/.aseprite file format).

Hi @dacap. Yes, I have installed via .bat file, tried uninstalling and changing the directories of the .dll file, tried clearing windows thumbnails, rebooted the PC, nothing works. I also checked if thumbnailer works on a virtual machine (yes, I ran Install.bat and even rebooted), still doesn't work:

![зображення](https://github.com/user-attachments/assets/55350b93-d470-4fb9-8434-b5d9fe586926)

**Comment by dacap** [comment] 2024-12-02 17:27
OK, I've dedicated some time to investigate this issue on Windows, here's the problem:

1. The `.ase` / `.aseprite` extension (`HKEY_CLASSES_ROOT\.aseprite`) might be associated to the `aseprite_auto_file` class when it's associated through "Default apps" section of Windows:

  ![image](https://github.com/user-attachments/assets/a35091d4-8643-429a-a0ed-65d6b256ffec)

2. The `HKEY_CLASSES_ROOT\aseprite_auto_file` class points to the portable version to open files:

  ![image](https://github.com/user-attachments/assets/d89cd5d9-2ff3-4b99-a9f3-1d75b61d8109)

3. But the information of the thumbnailer is in the `AsepriteFile` class:

  ![image](https://github.com/user-attachments/assets/7b81915d-7b52-4c12-ba62-5c6ea96fa7f3)

To manually fix this, one possiblity is to change the `HKEY_CLASSES_ROOT\.aseprite` value to `AsepriteFile` (as it's when the installer is executed):

![image](https://github.com/user-attachments/assets/068ba893-5f3f-417e-a236-b1f791bee689)

And to copy the `HKEY_CLASSES_ROOT\aseprite_auto_file\shell\open\command` info to `HKEY_CLASSES_ROOT\AsepriteFile\shell\open\command`.

In some way we could fix this implementing #1179, with a section in Preferences to 1) associate the .aseprite files with the running Aseprite.exe (portable version / installed version), and 2) include the thumbnailer in the portable version.

**Comment by ElderlyGlek** [comment] 2024-12-02 22:08
> And to copy the `HKEY_CLASSES_ROOT\aseprite_auto_file\shell\open\command` info to `HKEY_CLASSES_ROOT\AsepriteFile\shell\open\command`.

The path "HKEY_CLASSES_ROOT\AsepriteFile\shell\open\command" does not exist:

![](https://github.com/user-attachments/assets/5278d149-2026-4a9e-895e-2a41c0a23399)

> In some way we could fix this implementing #1179, with a section in Preferences to 1) associate the .aseprite files with the running Aseprite.exe (portable version / installed version), and 2) include the thumbnailer in the portable version.

Is issue #4675 a duplicate?

**Comment by dacap** [comment] 2024-12-02 23:11
> The path "HKEY_CLASSES_ROOT\AsepriteFile\shell\open\command" does not exist:

That's why I was saying that to fix this manually (at the moment) you have to copy the `HKEY_CLASSES_ROOT\aseprite_auto_file\shell\open\command` into `HKEY_CLASSES_ROOT\AsepriteFile\shell\open\command` (creating the folders and same values).

The other way around should work too: copy the whole `HKEY_CLASSES_ROOT\AsepriteFile\ShellEx` folder into `HKEY_CLASSES_ROOT\aseprite_auto_file`.

The idea is that the name associated to .aseprite / .ase (AsepriteFile or aseprite_auto_file) must contain both folders (`shell` and `ShellEx`).

I'll mark both of these issues as duplicate of #1179.

**Closed** 2024-12-02 23:11 UTC
Labels: duplicate, windows, help

**Comment by ElderlyGlek** [comment] 2024-12-02 23:54
I hope this will be fixed in the near future.
