### ISSUE TITLE
SUGGESTION: Layer blend mode and layer opacity should accessible straight from main UI

### ISSUE THREAD

**Issue by trollworkout** [aseprite/aseprite#1296] opened 2016-10-17 04:46 UTC
Perhaps add an option next to Position lil button where you can quickly pop out a panel similar to the way Position does it to set Opacity / Layer properties / Blend Mode in addition to  Right Click/Properties in context menu.

**Comment by dacap** [comment] 2016-10-18 02:10
I think duplicate of #1052

**Closed by dacap** 2016-10-18 02:10 UTC
